### ISSUE TITLE
Inscripción grupos

### ISSUE THREAD

**Issue by jeschuwirth** [IIC2413/Syllabus-2019-2#1]
Saludos,

¿Para inscribir los grupos es necesario que ambos integrantes llenen el formulario o basta con que uno lo haga?

Pregunto ya que en los ramos que he tomado prefieren que uno solo inscriba y el otro no envíe una respuesta.

**Comment by nivek0o0** [comment]
Hola @jeschuwirth 

Basta con que 1 integrante del grupo lo envíe.

Saludos!
