### ISSUE TITLE
ModuleNotFoundError: No module named 'BTrees'

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#100]
Hola
¿ Debo instalar algún modulo aparte para poder usar la librería ?, he buscado información y no he encontrado nada bueno :(, me aparece el siguiente error cuando importó la librería en pyhton (3.6) o juptyter
![image](https://user-images.githubusercontent.com/42189869/65700864-bc271d00-e056-11e9-8f2d-1293d4f50125.png)
Saludos !

**Comment by arbiocanpion** [comment]
Hola!
¿Que sistema operativo usas?

**Comment by Tngarrido** [comment]
probé con "pip install BTrees" y me resulto, gracias!
