### ISSUE TITLE
problema datos BIG

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2413/Syllabus-2019-2#103]
Hay una tupla que tiene solo el id del usuario y no tiene el de la pelicula, esta echo a proposito eso o es un error? es la tupla de id 4338 del archivo favoritos.csv big

**Comment by arbiocanpion** [comment]
Hola!
Eso no es un error, la idea de la actividad es que ustedes sepan manejar los casos en los que no hay match del userId.

**Comment by Kitaps** [comment]
Habría sido bueno que los datos small tuviesen estos mismos problemas para manejarlos de antes y luego en big solo preocuparnos de que funcione bases de datos grandes. ;)
