### ISSUE TITLE
Actividad 2.2 que estructura retornar

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2413/Syllabus-2019-2#104]
Hola! No me queda claro que tengo que retornar en la parte 2.2 como resultado del join de los btrees de usuarios y favoritos. Tiene que ser un btree? O puede ser una lista/tupla?
Saludos!

**Comment by arbiocanpion** [comment]
Hola!
Puedes retornar una lista o tupla, no es necesario que se retorne un btree.

**Comment by BenjaPrograma** [comment]
Gracias!, una pregunta más con respecto a la parte 3 cuando dice:

> La idea es que se utilice el hash join para extender la información de cada pelicula con la que hace match.
esto se refiere simplemente a acceder al diccionario mediante la key o me estoy perdiendo algo?

**Comment by arbiocanpion** [comment]
¡Tu mismo lo dijiste!
Éxito con la actividad

**Comment by BenjaPrograma** [comment]
gracias!
