### ISSUE TITLE
Nombres archivos distintos

### ISSUE THREAD

**Issue by stmorales** [IIC2413/Syllabus-2019-2#106]
Hola! En  los datos de la carpeta small el archivo de los usuarios se llama "usuarios". En cambio, en la carpeta big se llama "nombres_b". Se va a corregir de esta manera o podemos suponer que ambos van a tener el mismo nombre?

**Comment by juanreutter** [comment]
Hola, pueden usar el nombre que quieran, con el path que quieran.
