### ISSUE TITLE
Subir archivo PDF

### ISSUE THREAD

**Issue by ninifdr** [IIC2413/Syllabus-2019-2#11]
Para subir el archivo PDF tengo que subir el archivo al servidor codd.ing.puc.cl ó grupoXX@codd.ing.puc.cl ?
En el enunciado sale que hay que subirla a codd.ing.puc.cl, pero me pide una contraseña y no se cuál poner.
Gracias!

**Comment by nivek0o0** [comment]
Hola @ninifdr 

la dirección del servidor es **codd.ing.puc.cl** (a la cual se accede por el navegador). Tu usuario en el servidor es **grupoXX**, tu contraseña por defecto es **grupoXX** (a menos que haya sido cambiada previamente con el comando _passwd_)

El comando para acceder al servidor tiene la sintaxis: `ssh <usuario>@<direccionServidor>`
que en este caso sería `ssh grupoXX@codd.ing.puc.cl`

**Comment by ciquezada** [comment]
Hola,
Y en la wiki dice que se recomendaba entregar el pdf en "~/Sites/EntregaX", pero en el pdf de la entrega dice que sea en "~/EntregaX/"
¿A cual le hacemos caso?

**Comment by nivek0o0** [comment]
Siempre al enunciado!
