### ISSUE TITLE
Parámetros "hardcodeados"

### ISSUE THREAD

**Issue by SergioGazali** [IIC2413/Syllabus-2019-2#110]
Hola!
Cuando en la parte 3 se nos pide programar una consulta, ¿se refiere a que nuestra función efectivamente esté construida para poder recibir distintas tablas que desconocemos? Por ejemplo, yo sé que el atributo que determina el join está en la posición cero de una tupla.
¿Es posible escribir `if u_tupla[0] == f_tupla[0]:` o debo reconocer desde la consulta qué atributo se me pide en la sección `WHERE...` y luego encontrarlo en la tupla para compararlo y hacer el join?
Muchas gracias!

**Comment by arbiocanpion** [comment]
Hola!
No es necesario realizar un algoritmo tan avanzado, basta con que se pueda realizar para los archivos que subimos.
