### ISSUE TITLE
Hash join

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#111]
Hola. En la actividad se pide hacer usar el hash para agregar los atributos restantes a la tupla. Debo asumir que cada vez que se necesite yo voy a encontrar el valor de la tupla en el diccionario de hash?

Me refiero a, si tengo un match entre usuario.id y favorito.user_id, entonces favorito.movie_id va a estar siempre en peliculas?

**Comment by arbiocanpion** [comment]
Hola!
Si, puedes asumir que todos los ids de las películas existiran.

**Comment by JJJGGGG** [comment]
Hola. Bajo esta misma suposición, me sale este error al usar los datos grandes

```
KeyError                                  Traceback (most recent call last)
<ipython-input-15-edaeeb61b83b> in <module>
     34 t1 = time()
     35 
---> 36 join_tablas(usr_tree,h_mov,fav_tree)
     37 
     38 print("Tiempo en crear arboles y hacer el join: {}s.".format(t1 - t0))

<ipython-input-10-a9661aafd652> in join_tablas(usuarios, peliculas, favoritos)
      7     while next_usr and next_fav:
      8         if next_usr.tupla[0] == next_fav.tupla[0]:
----> 9             full_join.append((next_usr.tupla[1], next_usr.tupla[0], next_fav.tupla[1], peliculas[next_fav.tupla[1]][1]))
     10             next_usr = next_usr.siguiente
     11             next_fav = next_fav.siguiente

KeyError: nan
```
Evidentemente, es porque la id de la pelicula referenciada no existe en la tabla de hash. Se puede usar ```in``` para ver si la llave está en el diccionario?

**Comment by arbiocanpion** [comment]
Disculpa, hubo un error de mi parte.
Si el usuario ´´TIENE´´´ una movieId favorita, esta estara en el archivo, pero puede darse el caso que el usuario no tenga una película favorita, que es el caso en que la llave valga Nan.
Queda a tu criterio como manejar aquellas excepciones, pero no puedes eliminar los userId que no tienen pelicula favorita.

**Comment by valeeeriquelme** [comment]
@arbiocanpion lo de que no se pueden eliminar los usuarios sin pelicula favorita, tambien aplica para la parte del join? (2.2)

**Comment by arbiocanpion** [comment]
@valeeeriquelme, si. La idea es que tu codigo pueda manejar la excepción en la base de datos.

**Comment by valeeeriquelme** [comment]
La verdad es que no me queda muy claro a lo que se refiere con no poder borrar los usuarios que no tienen película favorita...por ejemplo en la 2.2 eso significaría que también debo mostrar a aquellos usuarios sin película favorita? Y en la parte 3 tendría que mostrarlos a ellos y también la info de las películas que no estan en la tabla "Favoritas"?

**Comment by arbiocanpion** [comment]
No es necesario que muestres los usuarios que no tienen película favorita.
