### ISSUE TITLE
Lugar de entrega actividad 2

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#112]
Una pregunta rápida: dónde hay que entregar la actividad?

**Comment by arbiocanpion** [comment]
En el siding hay un cuestionario habilitado para que entreguen el jupyter notebook.

**Comment by absoto4** [comment]
Se pueden hacer entregas parciales?

**Comment by arbiocanpion** [comment]
@absoto4 mañana en la mañana te confirmo, pero según yo siding por default siempre deja que subas versiones a la entrega

**Comment by NicolasCastillo24** [comment]
Se entrega el archivo .ipynb nomas?

**Comment by arbiocanpion** [comment]
@NicolasCastillo24 si.
