### ISSUE TITLE
Parte 5

### ISSUE THREAD

**Issue by imunoz3** [IIC2413/Syllabus-2019-2#113]
Hola! Entiendo que en la parte 5 hay que comparar los tiempos de ejecución de los distintos códigos, pero no me queda claro que hay que hacer cuando dice "Primero debes considerar que los índices ya están creados para luego comparar los tiempos de ejecución considerando que tu Join primero crea los índices y después computa el resultado."  Gracias!!

**Comment by arbiocanpion** [comment]
El enunciado se refiere a que en el primer caso debes realizar el join con el Btree que ya generaste. Para el segundo caso ademas de realizar el join con el Btree, debes contabilizar el tiempo que demora generar el Btree a partir de los datos
