### ISSUE TITLE
Carpeta Big

### ISSUE THREAD

**Issue by Deleon20** [IIC2413/Syllabus-2019-2#117]
Hola! Tenia una duda sobre usar los archivos de la carpeta Big, podemos descomprimir los archivos y trabajarlos después en python o debemos descomprimirlos a través de python mismo y desde ahí trabajarlos?

**Comment by arbiocanpion** [comment]
Hola!
Puedes descomprimir los archivos y despues trabajarlos en python.

**Comment by Deleon20** [comment]
Ya muchas gracias!
