### ISSUE TITLE
Nested loop: for o while

### ISSUE THREAD

**Issue by SergioGazali** [IIC2413/Syllabus-2019-2#118]
Hola!
Al pedirnos que el código del nested loop join se vea como tres `for` anidados, es realmente importante el 'for'? porque con los btrees se me hace más intuitivo anidar whiles en los que recorro con `.siguiente`
Muchas Gracias!

**Comment by arbiocanpion** [comment]
Hola!
La idea del nested loop es que no recorras los datos almacenados en Btrees, sino que uses listas para almacenar los datos y hacer el join.
