### ISSUE TITLE
Qué es un join según las slides?

### ISSUE THREAD

**Issue by jearaneda** [IIC2413/Syllabus-2019-2#119]
Estoy confundido con la 2.2 porque no veo en dónde se define lo que es un join en términos de programación y tampoco lo encuentro en internet.

Lo que estaba haciendo hasta ahora era asumir que los usuarios de Favoritos siempre existen, e iterar por las películas para luego insertarle el nombre personas (JOIN Favoritos x Usuarios), pero leyendo las issues veo que al parecer no es la idea.

Se me ocurren dos cosas a partir de las slides, pero creo que ambas están mal:

1) recorrer uno de los trees, digamos Usuarios, e insertar en la lista join el id, si es que Usuarios.id "in" Favoritos. El problema es que estaría recorriendo cada usuario y la lista de favoritos en cada iteración, y quedaría que la cantidad de iteraciones es = len(usuarios) + len(favoritos)*len(usuarios. Pero más que nada viendo las slides parece que esto sería un nested loop join.

2) A partir de lo que sale como "Supondremos solamente restricciones de igualdad (por ejemplo, R.a = S.a)" podría ser lo mismo que armé, pero en un try catch (que tirará error si cierto índice no existe en usuarios). De nuevo, creo que esto no sirve según #108 y #94, pero estaría cumpliendo con el requisito del jupyter "que solo pase una vez por cada tupla de cada relación".

gracias!

**Comment by arbiocanpion** [comment]
Hola!
En primer lugar, un join en programacion se podria definir como

```python
from collections import defaultdict
s_p_t_t=[]
hash_= defaultdict(list)
for idx, row in enumerate(shops_products):
    hash_[row[0]].append(idx)

for row in tags_taggings:
    if row[3] in hash_:
        for x in hash_[row[3]]:
            s_p_t_t.append(shops_products[x]+row)
```

Lo que podrías hacer respecto a tu problema es usar el metodo .has_key() que tienen el OOBtree, la cual te permite identificar si una llave esta o no esta en el Btree, con esto podrías con algun if, generar alguna restriccion que si no se cumple, rellene con un dato de default.

**Comment by juanreutter** [comment]
@jearaneda tu sabes lo que es un join, y por supuesto que NO hay que asumir que siempre hay un match, nunca en clases lo hemos hecho. En terminos de programación, se trata de realizar codigo para poder levantar esa información. Lo más simple computacionalmente es el nested loop, como lo que puso @arbiocanpion. Lo que pedimos en la actividad es lo que corresponde a un merge join con índice, que es una forma mucho más eficiente de hacerlo. 

Ahora por supuesto, ¡ese algoritmo no lo vas a encontrar en las slides! ¿Cómo funciona? lo más simple es pensar en las listas R y S del 2.1. A punta de R.next y S.next, nosotros podemos encontrar la intersección de R y S pasando una vez por R y S. Luego de eso, puedes usar la navegación que le damos a la estructura de la actividad para simular ese mismo algoritmo, ahora en las llaves de las tablas de usuarios y favoritos.
