### ISSUE TITLE
Entrega de Proyecto

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#12]
Hola,
Quiero preguntar por la base de datos en el servidor, en donde se encuentra? o hay que crearla en la misma carpeta de entrega?, esa parte no entiendo y no sale mas información en el enunciado

Saludos

**Comment by nivek0o0** [comment]
Hola @ciquezada 

las bases de datos de todos los grupos son administradas por una aplicación instalada en el servidor llamada postgreSQL. Es bastante similar a SQLite. 

Para acceder a una consola dentro de la aplicación basta con escribir el comando **psql** en la terminal de ubuntu. Una vez dentro podrás crear, poblar y consultar tablas, para lo cual te sugiero consultes la [documentación oficial](https://www.postgresql.org/docs/10/index.html) de postgres.
