### ISSUE TITLE
datos big

### ISSUE THREAD

**Issue by jcechavarri** [IIC2413/Syllabus-2019-2#120]
Hola!

Escribiendo la conclusión, me fijé que la base de datos big tiene líneas con 3 datos, por ejemplo la línea 3107 es:

3106,Cerro, Print

debemos manejar este tipo de casos o se considera un error? Normalmente si la segunda parte es un nombre, se escribiría como 3106,'Cerro, Print' para saber que se debe ignorar la segunda coma o no?

Gracias!

**Comment by arbiocanpion** [comment]
Hola!
Es un error, pero para el desarrollo de la actividad, no debería afectar, ya que solo necesitas el id para la actividad.

**Comment by jcechavarri** [comment]
Gracias! Esque estaba cargando los datos con pandas, por lo que se me cae al cargarlos. Los cargo de otra forma para big entonces!
