### ISSUE TITLE
tiempo datos

### ISSUE THREAD

**Issue by jcechavarri** [IIC2413/Syllabus-2019-2#121]
Hola! 

Para la conclusión nos piden comparar los tiempos entre los dos tipos de consultas en los datos big. La forma nested loop join se me demora 10 minutos con la base de datos small, ¿cómo se supone que corra la consulta con la base big, que es muchísimo mas grande?

Gracias!

**Comment by arbiocanpion** [comment]
Hola!
En la issue #98 se respondio aquella duda.
