### ISSUE TITLE
'NodoBTree' object has no attribute 'siguente'

### ISSUE THREAD

**Issue by saanios1** [IIC2413/Syllabus-2019-2#123]
No me dejan usar el siguente, aun que tengo "from BTrees.OOBTree import OOBTree"
<img width="733" alt="Screen Shot 2019-09-30 at 10 37 50 PM" src="https://user-images.githubusercontent.com/18551422/65910379-3b0fb300-e3d3-11e9-8d3c-915af241a716.png">

**Comment by arbiocanpion** [comment]
Estimado en la linea 11 debería decir favorito_actual.siguiente, en vez de siguente.
