### ISSUE TITLE
'NodoBTree' object is not subscriptable or has no attribute "values" - como usar el NodoBTree?

### ISSUE THREAD

**Issue by saanios1** [IIC2413/Syllabus-2019-2#124]
<img width="747" alt="Screen Shot 2019-09-30 at 11 44 42 PM" src="https://user-images.githubusercontent.com/18551422/65915718-a27e3080-e3dc-11e9-8b54-d3166e1abc19.png">
<img width="873" alt="Screen Shot 2019-09-30 at 11 45 45 PM" src="https://user-images.githubusercontent.com/18551422/65915733-aa3dd500-e3dc-11e9-9af0-8f1ec3d6a200.png">

**Comment by arpincheira** [comment]
Hola,
Recuerda que tu mismo defines tu b-tree dentro de la actividad, y este cuenta con un atributo denominado tupla(por lo menos en el ejemplo dado es así), probablemente lo que quieres/debes hacer es referencia a usuario_actual.tupla[0] y no usuario_actual[0] dado que este último no va a existir.
Espero haberte ayudado.
