### ISSUE TITLE
Bug SQL 

### ISSUE THREAD

**Issue by Kitaps** [IIC2413/Syllabus-2019-2#125]
Hola, 

hemos estado teniendo problemas para poder hacer la tercera función de la actividad. 

Nuestro codigo es: 
`CREATE OR REPLACE FUNCTION leng()
RETURNS INTEGER AS $$
DECLARE
    tupla RECORD;
    count integer;
BEGIN
    count := 0;
    FOR tupla IN SELECT * FROM Personas LOOP
        CASE WHEN tupla.run LIKE '%K%' THEN count := count + 1;
            ELSE SELECT 1; 
        END CASE;
    END LOOP;
    RETURN count;
END
$$ language plpgsql;`

Lo que nos tira el error:

`ERROR:  query has no destination for result data
HINT:  If you want to discard the results of a SELECT, use PERFORM instead.
CONTEXT:  PL/pgSQL function leng() line 9 at SQL statement`

No sabemos que significa este error. Ya que en la fucnión 2 era practicamente lo mismo y no tiraba error. Además buscando en google sale que hay que entregarle un return, que está. Que está mal?

De antemano muchas gracias.

**Comment by arpincheira** [comment]
Hola, 
Estaba buscando información sobre su error y lo que sucede específicamente es que su select 1 es aquel que está generando el error de la función, yo les aconsejaría personalmente que cambien eso por un ```count := count + 0;``` ya que eso estaría cumpliendo la función de no hacer ningún cambio en caso de que el rut analizado no tenga k.

De todas maneras, dado que en este caso solo existe una opción en la que se debe actuar, yo recomiendo fuertemente no utilizar el CASE statement, dado que hay soluciones mucho más simples de usar.

Lamento la tardanza y espero haber sido de ayuda.

**Comment by juanreutter** [comment]
era eso? Grande @arpincheira me tenía mal este problema!
