### ISSUE TITLE
No funciona la página del proyecto

### ISSUE THREAD

**Issue by nhbravo** [IIC2413/Syllabus-2019-2#127]
Hola, mi [link del proyecto](http://codd.ing.puc.cl/~grupo35/index.php) no funciona, según Google Chrome, "codd.ing.puc.cl no puede procesar esta solicitud en este momento.", alguien sabe por qué puede ser?
Saludos.

**Comment by nivek0o0** [comment]
Hola,
el servidor se encuentra funcionando correctamente. De hecho creé un archivo llamado `index2.php` y se muestra correctamente en tu Sitio. 
El problema está en tu archivo, tal vez algún error de sintaxis. (Por eso el error es de tipo 500)

Saludos
