### ISSUE TITLE
Modificación página servidor

### ISSUE THREAD

**Issue by daleal** [IIC2413/Syllabus-2019-2#128]
Hola! Quería probar una nueva versión de nuestra página en el servidor pero no sé cómo funciona la corrección de la entrega pasada. Puedo modificarla? O debo esperar a que sea corregida la entrega anterior?

**Comment by arpincheira** [comment]
Hola,
No te preocupes con respecto a la modificación de tu página, ustedes tienen acceso libre tanto a sus archivos como a su base de datos de grupo. Las modificaciones que hagas a esta no tendrán repercusiones con respecto a la corrección de la entrega pasada.

Espero haber sido de ayuda

**Comment by daleal** [comment]
Muchas gracias!
