### ISSUE TITLE
Correr aplicación de forma local

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#129]
Hola, existe alguna forma de correr mi aplicación de forma local y no tener que estar trabajando constantemente con la que se encuentre en el servidor?

**Comment by arpincheira** [comment]
Hola,
existen múltiples maneras de correr tu aplicación directamente por tu computador, pero no las recomendaría mucho debido a que tienes que descargar aplicaciones adicionales para poder administrar tu base de datos y para poder montar un servidor local.
Dentro de lo que viene siendo una recomendación, podrías añadir una nueva carpeta dentro de la carpeta sites en la que crees tu aplicación y puedas ir probando diversas funcionalidades sin la necesidad de tener que modificar en si los archivos que serían finalmente considerados para la entrega.

De todos modos, una app que parece ser bastante recomendada para hacer lo que quieres es XAMPP, pero yo creo que lo más sencillo sería considerar otra opción como la que te mencioné anteriormente.

Adicionalmente, si quieres probar principalmente lo que vienen siendo las vistas que vas a utilizar en la aplicación, debes considerar crear archivos html los que podrías ver de forma local sin tener que instalar necesariamente programas adicionales. Ojo con esto de todos modos porque al momento de subirlos al servidor o añadirle funcionalidades deberías crear un archivo de extensión .php en el que añadirías el código presente y lo que encuentres pertinente para que funcione en el interior de tu aplicación.

Espero haberte ayudado y perdón por la demora.
