### ISSUE TITLE
Pregunta psql

### ISSUE THREAD

**Issue by totichi** [IIC2413/Syllabus-2019-2#13]
Una vez estando en el servidor y ejecutando el comando psql grupo"xx" trato de crear tablas , pero no lo logro hacer, no me arroja nada devuelta tampoco. (se que no las crea porque no me responde a las consultas).
Dejo un ejemplo de una de las tablas:
`CREATE TABLE Hola(id int,stringsito char(30))`
`INSERT INTO Hola VALUES (1,dadada)`
`SELECT * FROM Hola`

al hacer esto,no de devuelve nada.

**Comment by cmp831** [comment]
Hola

Trata de separar los comandos con punto y coma `;`
