### ISSUE TITLE
Procedimientos, funciones sql o consultas directas desde php

### ISSUE THREAD

**Issue by Oisangui** [IIC2413/Syllabus-2019-2#130]
Para cualquier consulta ```CONSULTA1``` que se deba realizar desde la página web, qué es mejor?
-Tener una función en el servidor con el nombre ```CONSULTA1``` que realice la consulta, y luego llamar esa función por nombre desde la página web.
-Tener todo el código de la consulta en el código php de la página web y hacer la consulta directa al servidor.

Pienso que la segunda opción es poco ordenada, pero no sé si es recomendable la opción 1. Qué es mejor en el caso de consultas simples que no requieran procedimientos almacenados? Una función definida en el servidor sería la respuesta?

**Comment by arpincheira** [comment]
Hola,
Dentro de lo que viene siendo la seguridad de tu código y de tu base de datos, lo ideal sería la primera opción, ya que de este modo no dejaría ver a usuarios externos el código con el que realizas la consulta y por ende mantendrías en "secreto" el nombre de tus bases de datos por lo que una inyección de código para borrar tus tablas sería más difícil de realizar.
En el caso de la segunda opción, como ya mencionaste anteriormente, es mucho más desordenada y se pierde esta seguridad adicional que otorgaría la primera, permitiendo de cierto modo ver como realizaste tus consultas y dejando al descubierto el nombre de tus tablas y sus columnas.

En lo personal recomiendo mucho la primera opción, espero haberte ayudado
