### ISSUE TITLE
Ayuda creación barra de navegacion

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#131]
Estoy teniendo problemas para crear una barra de navegación (al cambiar su diseño más que nada) Al replicar el index de la forma html, me resulta bien, así que creo que debe ser algo así. No se si tienen alguna idea de donde podría estar el problema?

php:
![image](https://user-images.githubusercontent.com/47841749/66526695-f7eac980-eacf-11e9-9f82-16a28881cae9.png)

html:
![image](https://user-images.githubusercontent.com/47841749/66526703-fd481400-eacf-11e9-91d3-95f847f365ff.png)

Y mi barra de navegación se ve de la siguiente forma:

php:
![image](https://user-images.githubusercontent.com/47841749/66526776-29639500-ead0-11e9-823e-466183a625f9.png)

html:
![image](https://user-images.githubusercontent.com/47841749/66526796-35e7ed80-ead0-11e9-9013-3f4d6f7423a3.png)

PD: Se que en la imagen no hay ninguna clase navbar, pero era el mismo problema cuando lo hacía

**Comment by arpincheira** [comment]
Hola,
Estaba viendo el caso que dices y al parecer lo solucionaron, de todos modos para problemas de este estilo recomiendo utilizar lo que viene siendo la función de revisar el código de fuente de la página de los navegadores, encuentro que es bastante útil porque les indica a detalle que componente dentro de su código genera aquello que quieren modificar o eliminar.

Espero haberte ayudado
