### ISSUE TITLE
Error Llave Foranea y Joins

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2413/Syllabus-2019-2#132]
Hola! Corrigiendo la entrega 2 (grupo par), ocurría algo extraño queria setear como llave foranea la id de recursos , en la tabla que contiene solo los id de ongs y recursos, puesto que me decia que habian algunos IDS que se encontraban en la tabla anterior, pero no en la tabla de recursos.
La tabla de recursos la forme de la siguiente manera:

Donde recursos_temp es una tabla temporal que tiene aquellos datos, proyectos2 es la tabla proyectos, y comuna es la tabla de comunas.

CREATE TABLE recursos AS
SELECT
recursos_temp.rec_id,
recursos_temp.causa_contaminante,
recursos_temp.area_influencia,
recursos_temp.descripcion,
recursos_temp.fecha_apertura,
recursos_temp.estatus,
proyectos2.p_id,
comuna.com_id
FROM recursos_temp
INNER JOIN proyectos2 ON proyectos2.nombre = recursos_temp.nombre
INNER JOIN comuna ON comuna.nombre = recursos_temp.comuna

Sin embargo me di cuenta que si hacia LEFT JOIN en ambos, el problema se solucionaba, me queda la duda entonces de porque pasa esto. 
Saludos y gracias!

**Comment by juanreutter** [comment]
El LEFT JOIN adicionalmente te deja los recursos_temp.nombre que no hacen match en proyectos2, eso es todo. No sé si se te coló algun recurso que no está en proyectos2, los datos no deberían estar así pero quizá pasó por otro motivo. O puede ser lo mismo con los nombres de comuna. 

Hace el left join y fijate en las columnas que tengan nulos en el campo p_id o com_id y ahí vas a ver cuales no hacen match. 

----- 
Comentario aparte: no es buena práctica que la creación del esquema esté mezclada con la forma en que importas los datos. Lo ideal sería tener una sentencia que cree el esquema con los campos y tipos de datos correctos, y en otro lado un insert que saque de los temp.

**Comment by BenjaPrograma** [comment]
En ese caso hace sentido que el INNER JOIN me tirase error cuando tratara de hacer una llave foranea, puesto que van a faltar IDS. Mi pregunta ahora es si es correcto usar el LEFT JOIN, a pesar de que me deje recursos que no hagan match en proyectos. Porque sino no sabria como hacer un JOIN y también hacer que funcione la llave foranea.

Saludos!
