### ISSUE TITLE
Interconexión bases de datos

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#133]
Hola, estoy tratando de conectar ambas bases de datos, tal como se muestra en la siguiente [issue ](https://github.com/alanezz/Syllabus-2019-1/issues/95) del semestre pasado, sin embargo me tira error con la conexión del otro grupo, he estado un buen rato pensándola, pero me sigue tirando el mismo error y no entiendo por qué, dice que es un problema de validación de ontraseña pero no me hace sentido ya que es correcto ese mach user/password del grupo par. Espero me puedan ayudar.
![Captura de pantalla de 2019-10-10 16-34-10](https://user-images.githubusercontent.com/47841749/66600662-5e2d2600-eb7c-11e9-8ffc-cf88ae5c46d3.png)
![Captura de pantalla de 2019-10-10 16-34-47](https://user-images.githubusercontent.com/47841749/66600669-64bb9d80-eb7c-11e9-8089-ee435bbc2df0.png)
![Captura de pantalla de 2019-10-10 16-35-01](https://user-images.githubusercontent.com/47841749/66600672-65ecca80-eb7c-11e9-9bca-2ab2229d1550.png)

**Comment by cmp831** [comment]
Hola, ántes de responder la issue, deben tener en cuenta que el syllabus es una plataforma pública, significa que **cualquier persona puede ver estas issues**. Por lo tanto, **publicar cualquier tipo de contraseña es un riesgo de seguridad gigante.** **Deben** cambiar la contraseña de sus bases de datos lo más antes posible

Revisamos la configuración del servidor y todo parece en orden, pude conectarte a la bases de datos del grupo 65 sin problema. El problema al parecer es la contraseña del grupo 84, pueden verificar si la contraseña efectivamente es lo que llenaron?

**Comment by VicenteMerino** [comment]
Puede que ese sea el problema. Esa es la contraseña con la que me conecto al server desde la terminal (o filezilla). En este caso la contraseña de la base de datos vendría siendo igual a la original grupoXX?

**Comment by juanreutter** [comment]
Si, a contraseña de postgres es igual a la original. Puedes cambiarla si quieres, pero esto es un poco menos crítico por que solo tienen acceso a la BD los usuarios registrados del servidor.

**Comment by nivek0o0** [comment]
@VicenteMerino editar la issue para eliminar las contraseñas es totalmente inefectivo. Se puede acceder a la original de todos modos. 

Cambié las contraseñas de ambos grupos, ya que ustedes **aún no lo habían hecho.** Se las enviaré por correo. 

No nos haremos responsables si algo indeseado pasó en sus carpetas, ya que con esta issue expusieron el servidor, prácticamente, a todo el mundo.
