### ISSUE TITLE
De que forma se deben visualizar los recursos asociados a proyectos?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#134]
Bueno, lo que dice el enunciado, ya que en el esquema relacional no se incluye ni el nombre (el cual seria el mismo para todos los recursos asociados a un mismo proyecto), ni tampoco el numero. Entonces lo que se me ocurre es simplemente mostrarlos por su ID

**Comment by nivek0o0** [comment]
Hola @VicenteMerino 

El ID nunca se muestra al usuario final, porque no tiene ningún significado para él. Se me ocurre que podrías mostrar un Recurso según su causa_contaminante, área (si tiene), fecha y estatus. Con estos atributos es difícil que hayan 2 iguales.
