### ISSUE TITLE
dblink para acceder a otra base de datos

### ISSUE THREAD

**Issue by vahojas** [IIC2413/Syllabus-2019-2#136]
Hola! estoy intentando utilizar dblink para acceder a la base de datos del otro grupo en procedimientos almacenados, pero probando en la consola me aparece que la funcion no existe. Esto es porque solo sirve ocuparlo desde procedimientos almacenados o tiene otra causa? De antemano gracias.
![image](https://user-images.githubusercontent.com/42180838/66709085-16043400-ed33-11e9-85c1-508c41c8e126.png)

**Comment by VicenteMerino** [comment]
Te recomiendo ver esta [issue ](https://github.com/alanezz/Syllabus-2019-1/issues/95) De ahí lo saqué yo

**Comment by nivek0o0** [comment]
Hola @vahojas 
Lo que dice Vicente es para múltiples conexiones desde un archivo php. 

Lo que pasaba con la extensión **dblink** es que debía ser instalada. Ahora debería funcionar correctamente. Sirve tanto para consultas por consola como dentro de procedimientos almacenados. _(Ojo que en el string donde especificas los parámetros, la separación es mediante espacios solamente, no comas)_
