### ISSUE TITLE
Desplegar informacion que hereda

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#137]
Hola, cuando me piden por ejemplo, mostrar toda la informacion de un recurso, o mostrar los recursos, necesito mostrar (si es que tiene) fecha de dictamen (que es de una clase hija, recursos_cerrados), o esto no es necesario?

**Comment by nivek0o0** [comment]
Hola,
cuando muestres una lista de recursos asociados a otra entidad, bastan los atributos que mencioné en la #134.
Pero luego de que haces click en uno de ellos, se deben mostrar TODOS los atributos, incluyendo aquellos que pertenecen a la especialización.
