### ISSUE TITLE
De que forma se debe buscar los recursos?

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#138]
Cuál es la forma en que se buscan los recursos? De la forma "Recurso contra Celite"? Siento que hacerlo de esta forma es un poco raro, ya que el nombre no formaba parte de los atributos de los recursos.

Saludos

**Comment by nivek0o0** [comment]
te refieres a los proyectos o a los recursos?

**Comment by VicenteMerino** [comment]
Disculpa, me refería a los recursos

**Comment by nivek0o0** [comment]
Creo que lo más fácil para ustedes es que se busquen por la **causa_contaminante**

**Comment by ninifdr** [comment]
Hola! Solo para aclarar. Las ONG y proyectos se buscan por nombres y los recursos por causa contaminante?

**Comment by nivek0o0** [comment]
sí
