### ISSUE TITLE
Notas

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#139]
Hola, buenas tardes. Donde puedo ver las notas ya publicadas del curso? Por otro lado, ya publicaron las notas de la E1 y de la E2?

**Comment by nivek0o0** [comment]
Hola, las notas están en este [LINK](https://docs.google.com/spreadsheets/d/12DPjie7HGYQpL0rteuqLJd9jLDRlPzd80Gbcez_8tPo).

Las notas de la E1 fueron publicadas hace tiempo y las notas de la E2 estarán **hoy**.

**Comment by JaviFerrada** [comment]
Hola! como es el proceso de recorrecion?

**Comment by nivek0o0** [comment]
@JaviFerrada 

Se envían en este [Formulario](https://forms.gle/KLgqS17HKfPmEHLV9).
