### ISSUE TITLE
Duda psql importar datos de un csv

### ISSUE THREAD

**Issue by MGilB** [IIC2413/Syllabus-2019-2#14]
Hola, tengo el siguiente problema
Tengo un archivo csv en el servidor pero al usar el comando de la wiki `/COPY...`. , me aparece que no existe el archivo que quiero copiar, pero por lo que me aparece en filezilla si lo subí.

**Comment by cmp831** [comment]
Hola

Probé el comando y está funcionando. El comando funciona con el path relativo donde ejecutarse `psql` en la consola. Asegúrate poner el path relativo a tu csv.
