### ISSUE TITLE
Separación Minerales 

### ISSUE THREAD

**Issue by fbpesenti** [IIC2413/Syllabus-2019-2#140]
Hola! 
Tengo una duda sobre el diagrama E/R en la planilla de notas que a muchos grupos impares se les descontó 0,2 decimas porque faltaba separación de minerales. Y con mi grupo no entendemos a que se refiere para arreglarlo.
Saludos

**Comment by nivek0o0** [comment]
Hola @fbpesenti 

Se refiere a que no consideraron todos los minerales que podía tener un proyecto de tipo **mina** que indicaban los Datos. Por lo tanto, hay pérdida de información o bien está mal modelado. 

En la issue #61 se dijo que lo más correcto era considerarlos todos.
