### ISSUE TITLE
entrega3

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#141]
Hola
![image](https://user-images.githubusercontent.com/42189869/66778114-2803e500-eea1-11e9-9fe0-1862afca4e9a.png)

¿ que es lo que debe haber en aquella carpeta ? 
Saludos

**Comment by nivek0o0** [comment]
`tu_procedimiento_almacenado.sql`
Aquel que genera las movilizaciones en base al input

**Comment by Tngarrido** [comment]
@nivek0o0 
es decir, debo tener subir una copia del código de mi función que genera las movilizaciones en base al input ?
Saludos !

**Comment by nivek0o0** [comment]
@Tngarrido sí, debe haber allí una copia para que podamos corregirlo directamente.
