### ISSUE TITLE
Usuario logeado vs no logeado 

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#142]
Hola
![image](https://user-images.githubusercontent.com/42189869/66786486-dcf4cc80-eeb6-11e9-8c32-abb1c85aff40.png)
Como se indica en la imagen siguiente, la opción que permite hacer la búsqueda del nombre de un proyecto, una ONG o un recurso, solo será para aquello usuarios que han iniciado sesión. Osea intuyo esto, debido a que el buscador también permite obtener recursos, y como la imagen anterior no abarca recursos para un usuario que no ha iniciado sesión. Pero de todas formas quería preguntar, Saludos!.
 
![image](https://user-images.githubusercontent.com/42189869/66786643-7d4af100-eeb7-11e9-8e25-fc523154ef86.png)

**Comment by nivek0o0** [comment]
Hola, es verdad que el enunciado no quedó claro sobre las acciones que pueden realizar cada tipo de usuario. Por esa razón, lo explicaré aquí:
- Los **usuarios no logeados** deben poder realizar los primeros 3 items del enunciado: Navegación, Detalles y Búsqueda.
- Los **usuarios logeados** deben poder hacer todos los items, osea los 3 anteriores + Login + Planificación.

Entonces la respuesta a tu pregunta es que una busqueda de recursos no implica que tenga que poder ver la lista completa de recursos, por lo que tu intuición no es correcta

**Comment by Tngarrido** [comment]
okey @nivek0o0  ahora si me quedo claro !
