### ISSUE TITLE
Error al usar dblink para insertar datos en otra bdd

### ISSUE THREAD

**Issue by vahojas** [IIC2413/Syllabus-2019-2#144]
Hola! estoy teniendo problemas para insertar valores en una base de datos usando dblink. Creé una función "insert_march" que recibe como input los valores a insertar y debería insertar en la tabla del otro grupo los valores usando bdlink_exec. El código es el siguiente:
![image](https://user-images.githubusercontent.com/42180838/66860389-7da0c600-ef63-11e9-9189-c373ca5773f9.png)
Y cuando intento ejecutar la función me sale el siguiente error:
![image](https://user-images.githubusercontent.com/42180838/66860439-94471d00-ef63-11e9-942f-8adea856a1bf.png)
Busqué en la documentación y ejemplos en StackOverflow y sigo sin entender qué puede estar mal. Intenté cambiar los nombres de las variables para que coincidan con los nombres de los atributos de la tabla y me sigue saliendo el mismo error ¿Me podrían echar una mano con qué está mal? Gracias de antemano

**Comment by cmp831** [comment]
Hola, su implementación de la función tiene un error de sintaxis, dado que en ningun momento el string que estan ingresando para la función `dblink_exec` está considerando los variables. Por lo tanto, pueden usar una concatenación de texto, o bien la funcion `format` de plpgsql. 

Un ejemplo simple que creé para testear el funcionamiento usando format es lo siguiente:
```PLpgSQL
CREATE OR REPLACE FUNCTION insert_match(id int, name varchar) RETURNS VOID AS $$
DECLARE insert_command TEXT;
BEGIN
    PERFORM dblink_connect('conn', 'CONNECTION_STRING');
    insert_command := format('insert into simpletest values(%s, ''%s'');', id, name);
    RAISE NOTICE 'SQL = %',insert_command; 
    PERFORM dblink_exec('conn', insert_command);
    PERFORM dblink_disconnect('conn');
END;
$$ language plpgsql;
```
Tengan en cuenta de que deben escapar las comillas simples escribiendo dos veces la comilla simple `''`, no es una comilla doble `"`. La linea `    RAISE NOTICE 'SQL = %',insert_command; ` se encargará de imprimir el texto de insert_command, por lo que podrán debuggear el formateo. 

Cualquier otra pregunta pueden preguntar más abajo!

**Comment by vahojas** [comment]
Hola perdón por comentar tan tarde. Me funcionó super, gracias por la respuesta. Si no habría estado súper perdido con cómo manejar las variables con dblink.
