### ISSUE TITLE
Plazo Entrega Proyecto

### ISSUE THREAD

**Issue by manarea** [IIC2413/Syllabus-2019-2#145]
Estimados,

Considerando que la entrega del proyecto es este día viernes, quisiera consultar si existe la posibilidad de extender el plazo unos días. Sé que el tiempo (aunque sea uno o dos días) le serviría muchísimo tanto a mi como a mis compañeros. Por ello, si pudiesen considerar la posibilidad, sé que les estaríamos muy agradecidos.

**Comment by nivek0o0** [comment]
Los profes han decidido darles más plazo para esta entrega.

El nuevo **deadline** es el **Martes 22 de Octubre a las 20:00 hrs.**
