### ISSUE TITLE
LogIn y contraseña

### ISSUE THREAD

**Issue by SergioGazali** [IIC2413/Syllabus-2019-2#146]
Hola!
Intuitivamente pensamos que el login necesita una contraseña además del nombre y apellido. Sin embargo esto no se menciona en el enunciado del proyecto. Es necesario o se puede hacer login sólo con nombre y apellido??
Muchas gracias.

**Comment by nivek0o0** [comment]
Hola @SergioGazali 

**Sí** es necesario que implementen contraseñas para las ONGs y los Socios. Para ellos pueden modificar sus tablas como ustedes lo estimen conveniente.

Recuerden indicar en el Readme un par de credenciales para poder corregir.

**Comment by Kitaps** [comment]
las contraseñas tienen q estar encripatadas o podemos dejarlas así nomas?

**Comment by nivek0o0** [comment]
Para esta entrega es suficiente que estén en texto plano, pero si deseas experimentar puedes encriptarlas de todas formas.

**Comment by fbpesenti** [comment]
Para acceder en al login, los socios u ONGs tienen que ser solo las existentes en nuestras bases de datos o también pueden ser usuarios nuevos (por ejemplo, socios que nosotros inventemos)?

**Comment by juanreutter** [comment]
Si quieres puedes agregar esa funcionalidad también, pero en el proyecto solo pedimos que les des credenciales a los socios/ONGs ya existentes
