### ISSUE TITLE
Duda busqueda con Like

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#147]
Que pasa si al hacer la busqueda se encuentran 2 coincidencias? es decir, por ejemplo, 2 ongs que se parecen en el nombre, por lo tanto al mostrar los recursos asociados o movilizaciones estaríamos mostrando los de ambas ongs.

**Comment by nivek0o0** [comment]
Esa situación es un problema de navegabilidad. La forma fácil en que puedes resolverla es mostrar los resultados en una página sencilla y al hacer click en el link del resultado que deseas, te lleva a otra página con toda la información asociada.
