### ISSUE TITLE
Duda corrección entrega 2 BCNF

### ISSUE THREAD

**Issue by jfpena1** [IIC2413/Syllabus-2019-2#148]
Hola, a mi grupo se nos descontó en el criterio de BCNF, y esta fue la justificación :"-1 Comuna/Region dentro de Proyecto y Recurso".
Me parece raro esto porque en clases el profesor aclaró que era razonable asumir que no existía una dependencia funcional de la forma comuna -> region . Esto debido a que puede haber comunas con el mismo nombre en distinas regiones. De hecho, me parece haber revisado en su momento y creo recordar que habían casos en los que se daba esta situación.

Lo que nosotros hicimos fue dejar latitud y longitud en la tabla Proyecto y que ese par 
(latitud,longitud) fuese key de otra tabla Ubicacion que te permite acceder al dato de comuna y region con certeza. En la tabla recursos, como no se tenian datos de longitudes y latitudes se dejaron ambas la comuna y la region en la tabla por lo explicado anteriormente.

Quería saber si lo que hicimos realmente está mal o fue un error de corrección porque me imagino puede ser de utilidad para otros grupos. Muchas gracias !.

**Comment by clolate** [comment]
Yo recuerdo de la clase que le dijeron que las comunas eran únicas en nombre (como que el profe dijo no son únicas le dijeron si lo son y dijo me embarraste el ejemplo) , de hecho yo hice la suposición que eran únicas y me descontaron por mala práctica que se podían repetir los nombres.

**Comment by juanreutter** [comment]
Claro, si suponen que no hay comunas unicas entonces la dependencia no aplica. Y efectivamente eso lo discutimos en clases. Para corregir, es mas facil cuando esos supuestos losnponen dentro de la justificacion de bcnf (no se si es el caso).

**Comment by nivek0o0** [comment]
> De hecho, me parece haber revisado en su momento y creo recordar que habían casos en los que se daba esta situación.

@jfpena1  Tienes razón, hay comunas que se repiten en distintas regiones, pero esto es una inconsistencia de los datos, ya que en Chile el nombre de las comunas es único.

Dado lo anterior, vamos a re-corregir todos los informes en los que se descontó injustamente, pero solo si existe la justificación (como es tu caso). 

@clolate También vamos a re-corregir los casos en que se descontó por no usar un ID, ya que también es válido usar un nombre único como tal.
