### ISSUE TITLE
Consultas no funcionando.

### ISSUE THREAD

**Issue by hsazos** [IIC2413/Syllabus-2019-2#149]
![pantallazo_1](https://user-images.githubusercontent.com/48263455/66876794-7391be00-ef89-11e9-9796-16c8e30262d2.jpeg)
![pantallazo_2](https://user-images.githubusercontent.com/48263455/66876796-74c2eb00-ef89-11e9-9cff-7fecf32a39a2.jpeg)

Hola! En nuestra pagina web no nos están funcionando las consultas , no sabemos porque y llevamos un rato tratando. Nos lleva a una pagina en blanco, no tiene problema en conectarse con la base de datos (aparentemente). Podrían ayudarnos? 😞

**Comment by hsazos** [comment]
RESPONDANME Q

**Comment by nivek0o0** [comment]
Hola, la consulta se ve con una buena estructura, salvo el error de sintaxis en la linea 29 donde le pides 2 posiciones a un elemento de largo unitario (por el `select nombre`).

Si te refieres a las consultas 1 y 2 del grupo17, puedo ver los resultados en en el navegador  sin problemas
