### ISSUE TITLE
Procedimiento almacenado en base par

### ISSUE THREAD

**Issue by Oisangui** [IIC2413/Syllabus-2019-2#150]
En nuestro grupo, el grupo par tiene una tabla con los nombres de los proyectos, pero nada más, solo los nombres, y no las comunas por ejemplo. Debemos modificar la base de datos del grupo par para incluir las comunas de los proyectos involucrados? Tengo dudas al respecto ya que en la Entrega 1 solo se pedía una tabla con los nombres de estos.

Esto es relevante para el procedimiento almacenado porque toma como input la comuna y debe trabajar con todos los proyectos de esa comuna, lo que no podriamos hacer con como está la base de datos actualmente de manera interna. Se nos ocurrió manejar todo en php pero entonces ya no sería un procedimiento almacenado o sí?

En caso alternativo podríamos darle como input a la función una lista con todos los proyectos de la comuna necesaria?

Saludos.

**Comment by juanreutter** [comment]
Eso es parte del problema que tienen que resolver. La idea es que no modifiquen la base de datos, si no que trabajen con lo que tienen. Si eso implica dos procedimientos y no uno, bien!

**Comment by JJJGGGG** [comment]
Pero el hacerlo en php no constituye un procedimiento almacenado?

**Comment by juanreutter** [comment]
Claro que no. Mira las slides de la semana 6 o la primera frase en la actividad: "La mayoría de los DBMS ofrecen la posibilidad de programar funciones o procedimientos almacenados en el mismo DBMS."

**Comment by nivek0o0** [comment]
El grupo impar tiene una tabla de proyectos con más atributos.Esa es la gracia de juntar un grupo par y otro impar.
