### ISSUE TITLE
problema con llamado de function

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#151]
Hola!
Cuando llamó a mi función  "ProcedimientoAlmacenado" pasa que no se muestra nada en la pagína
![image](https://user-images.githubusercontent.com/42189869/66935207-0f670c80-f012-11e9-9adb-921c8ea6d402.png)

 sin embargo, si dejo todo el código del scope de mi función fuera y sin llamarla, me muestra lo que quiero.
![image](https://user-images.githubusercontent.com/42189869/66935036-cb740780-f011-11e9-8e9d-330ad06bfaf4.png)
Así defino mi función:
![image](https://user-images.githubusercontent.com/42189869/66935513-797fb180-f012-11e9-8c49-edc137292cfd.png)
llevo tiempo buscando soluciones, pero realmente no se que puede estar mal, gracias de antemano. 
Saludos !

**Comment by juanreutter** [comment]
Hola, la idea es que hagas un procedimiento almacenado en postgres, no una funcion procedimiento en php. Pero quizas algun maestro del php te puede ayudar mas con ese codigo.

**Comment by nivek0o0** [comment]
¿Por qué los parámetros de la función tienen un `&`?
