### ISSUE TITLE
Problema para ingresar a base de datos

### ISSUE THREAD

**Issue by totichi** [IIC2413/Syllabus-2019-2#152]
Cuando me meto al servidor todo bien, pero al momento de correr el comando psql me pide una contraseña la cual supongo que es la de mi grupo y no funciona. ayuda!

**Comment by crvargasu** [comment]
hola, puedes intentar con la contraseña inicial del servidor, es decir 'grupoXX', me pasó lo mismo y esa fue la solución

**Comment by nivek0o0** [comment]
Como dice @crvargasu , la base de datos tiene la misma contraseña por defecto que el servidor: `grupoXX`. Si esa no funciona, algún miembro de tu grupo la cambió.
Si nada funciona, avísame para resetearla.
