### ISSUE TITLE
Insertar valores en la base de datos desde php

### ISSUE THREAD

**Issue by crvargasu** [IIC2413/Syllabus-2019-2#153]
Hola, estoy intentando insertar nuevos valores desde php.

Lo estoy haciendo con el típico comando 
`$query = "INSERT INTO .....`

El problema me surge al ejecutar esa $query, no me funciona.
Lo estoy intentando de la siguiente forma:

`$result2 = $db ->prepare($query);
  $result2 -> execute();`

He buscado en internet, pero al parecer todos trabajan con mysql, y utilizan comandos diferentes

**Comment by cmp831** [comment]
Hola, la cunsulta deberia funcionar, sin ver el código es dificil saber cual es el error puntual que tienen. Un error común es que no agregan las comillas simples al rededor de un valor varchar o fecha.

**Comment by crvargasu** [comment]
Tienen comillas, la consulta es 
`$query2 = "INSERT INTO 
  proyectos VALUES('$pid','$tipo','$nombre','$lat','$long','$fecha','si');";
`
Todas las variables estan definidas anteriormente
 
Finalmente se ejecuta:
` $result2 = $db ->prepare($query2);
  $result2 -> execute();`

El archivo funciona perfectamente, solo que no edita la base de datos, no realiza la accion de insert into...

**Comment by nivek0o0** [comment]
Se me ocurre que puede estar fallando el INSERT en la base de datos porque no todas las columnas son de tipo **text**. Me imagino que pid y tipo fueron declarados como **int** al crear la tabla.

Cuando hice el proyecto, mi solución fue algo como ésto:
```
$sql = "INSERT INTO Usuarios VALUES (:mail, :nombre, :pass, :fecha)";
$statement = $db14 -> prepare($sql);
$statement -> execute( array(':mail'=> $mail,':nombre'=>$name,':pass'=>$password,':fecha'=>$date) );
```
Pruébalo para ver si te funciona! 

De hecho, esta es la manera de evitar el SQL Injection. Imagina alguien ingresara en tu último parámetro algo como: 

- `'loquesea'); DROP TABLE Usuarios;`

**Comment by crvargasu** [comment]
Ese era el error, ahora si pude solucionarlo.

Muchas gracias
