### ISSUE TITLE
Muestra de errores 

### ISSUE THREAD

**Issue by miortiz1** [IIC2413/Syllabus-2019-2#154]
![9D660C3B-5A76-47A8-B29F-BA157FE2AD2E](https://user-images.githubusercontent.com/37181021/66962829-61c32000-f048-11e9-82a4-8ed024950001.jpeg)

Se puede usar eso para ver los errores?

**Comment by cmp831** [comment]
Hola, sí lo pueden usar!

**Comment by nivek0o0** [comment]
Hola, los errores fueron habilitaron a nivel global para todos los grupos
