### ISSUE TITLE
Conexión remota a base de datos usando postgres_fdw

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#155]
Hola, quería saber, podemos usar la extensión postgres_fdw para conectarse a la base impar desde la par? En tal caso, la podrían instalar? (no podemos hacerlo nosotros porque no somos superusuarios)

**Comment by nivek0o0** [comment]
Hola, no sirve la extensión **dblink** que ya está instalada? De la cual hemos conversado en issues anteriores.
