### ISSUE TITLE
Problema PHP con comas

### ISSUE THREAD

**Issue by Deleon20** [IIC2413/Syllabus-2019-2#157]
Hola! Tengo un problema en la pagina y no se realmente como solucionarlo, la cosa es que mi pagina para todos los nombre que tengan una coma o un apotrofe solo muestra la parte del nombre antes de esto.
![image](https://user-images.githubusercontent.com/48283979/67024824-6e448880-f0db-11e9-8e89-9c822e350dec.png)
Sin embargo al buscarlo con el buscador me aparece correctamente 
![image](https://user-images.githubusercontent.com/48283979/67024951-9af8a000-f0db-11e9-9962-1e8865df3338.png)
Al igual que con cosas como "D'Amore" no me funciona la consulta  como tal al buscarlo o  clickearlo 
![image](https://user-images.githubusercontent.com/48283979/67025447-6f29ea00-f0dc-11e9-8e37-f57cd18bb8bf.png)
el resultado del buscador me sale 
![image](https://user-images.githubusercontent.com/48283979/67025477-7b15ac00-f0dc-11e9-944f-bbaff4ad7490.png)

**Comment by arpincheira** [comment]
Hola,
Podrías probar utilizando comillas dobles sobre tu variable dentro del archivo php con la consulta, algo como:

´´´
"$variable"
´´´
creo que eso podría solucionar tu problema

Espero haberte ayudado y avisa por aquí cualquier cosa.

**Comment by Deleon20** [comment]
Trate poniendolo en las variables pero me aparecio este error 😢 
![image](https://user-images.githubusercontent.com/48283979/67032000-19a80a00-f0e9-11e9-9a31-c16d8834082a.png)

**Comment by arpincheira** [comment]
em... estaba consultando y me recomendaron dos posibles soluciones para tu problema.

La primera de estas soluciones consiste en la concatenación de comillas simples, por lo que tu código se vería así: 
```echo 'mensaje' .$ variable.'.'; ``` 
o
```echo " {$ variable}"; ``` 

La otra opción sería probar con esto 
![image](https://user-images.githubusercontent.com/37157550/67042401-33078100-f0fe-11e9-99ec-5f66da94bcf4.png)

Avisa si alguna de estas te funciona, agradezco a @nivek0o0  y a @cmp831 por las alternativas aquí propuestas.

**Comment by Deleon20** [comment]
Gracias lo probe y me funciono!
