### ISSUE TITLE
Recursos vigentes

### ISSUE THREAD

**Issue by videvidts** [IIC2413/Syllabus-2019-2#158]
Hola tengo una confusión respecto a qué es un recurso vigente. Se que es uno aprobado o en trámite pero esto qué significa? Qué su fecha de dictamen es anterior a la fecha actual? Por favor si alguien me ayuda. Gracias.

**Comment by nivek0o0** [comment]
Hola @videvidts 
Todas las fechas en la base de datos son del pasado, por lo que no existen fechas mayores a la actual.
Esto implica que todos los recursos **aprobados** son "vigentes" (sin importar la fecha del dictamen) y todos los recursos **en trámite** también (no tienen fecha de dictamen).

**Comment by videvidts** [comment]
Entonces porque en la pauta hay una tabla de recursos cerrados? Que implica eso? Una tabla vacía?

**Comment by nivek0o0** [comment]
Recurso vigente **no** es lo mismo que recurso abierto. La vigencia la definimos como un recurso que afecta a un determinado proyecto (porque fue aprobado o porque podría serlo). Piensa en la mirada de los Socios: _¿Cuántos recursos vigentes tiene mi proyecto?_: 10 aprobados y 50 en trámite, _chuuta_

Lo de abierto o cerrado se refiere más bien al proceso de tramitación del recurso. 
- **Recurso abierto**: el proceso de tramitación aún no termina, por lo tanto el estatus siempre será `en trámite`. No tiene fecha de dictamen.
- **Recurso cerrado**: el proceso de tramitación terminó. El estatus puede ser aprobado/rechazado. Sí tiene una fecha de dictamen.

**Comment by videvidts** [comment]
Mil gracias!
