### ISSUE TITLE
Agregar datos csv a una columna

### ISSUE THREAD

**Issue by imunoz3** [IIC2413/Syllabus-2019-2#159]
Hola! Arreglando mi base de datos para la entrega 3 me di cuenta que una tabla necesita otra columna. Ya cree la columna en psql y ya tengo un archivo csv que contiene los datos. Como puedo usar el comando \copy from para importar los datos a esa columna solamente, sin necesidad de borrar todos los datos de la tabla. No me está dejando hacer lo último, porque dice que se viola la restricción de FK. Gracias!

**Comment by nivek0o0** [comment]
Hola, creo que el comando \COPY no soporta lo que deseas hacer.
Se me ocurre que podrías crear una tabla temporal para importar tu nueva columna, y luego usar conaultar estándar de postgres para copiarlos de una tabla a otra.
