### ISSUE TITLE
Subir pdf

### ISSUE THREAD

**Issue by jirarrazabal** [IIC2413/Syllabus-2019-2#16]
Hola!
Hay que subir la carpeta con el pdf a la carpeta grupoXX/Sites o solo a grupoXX?
Muchas gracias!

**Comment by nivek0o0** [comment]
Hola @jirarrazabal 

En el enunciado se indicaba que el _pdf_ debía ser subido en la carpeta `grupoXX/Entrega1`.  Este requisito tiene el objetivo de facilitar la recolección de las entregas y evitar que otros grupos puedan ver tu reporte desde el navegador.

La carpeta `Sites` será utilizada cuando empiecen a trabajar en su aplicación web, para que sea accesible desde el navegador.

**Comment by jerrymendoza** [comment]
Hola @nivek0o0,
En la wiki, en 'Tutorial de Servidor', en el apartado de 

> Subir archivos del proyecto al servidor **(Entregas 1 a 5)**

- Mencionan que es de la Entrega 1 a 5
- Las rutas siempre hablan de Sites/EntragaXX, y el código explícito para la entrega 1:
`scp  -r  grupoXX@codd.ing.puc.cl:~/Sites/Entrega1/ .` (por ejemplo).

Dado lo anterior, es posible considerar para esta entrega los documentos dentro de Sites?
En el caso de mi grupo, lo subimos a Sites/Entrega1
(lo que en el navegador corresponde **grupoXX/Entrega1**)

Ahora intentamos copiar a la otra ruta (para asegurarnos) pero no fue posible acceder con nuestra contraseña. Eso es para no hacer cambios fuera de horario? o nosotros tenemos un problema? 

Gracias!

**Comment by santilaguna** [comment]
Nos pasó lo mismo, de hecho lo habíamos subido a grupo26/Entrega1 y después lo cambiamos por lo que decía la wiki y el comando

**Comment by nivek0o0** [comment]
A raíz de esa ambigüedad consideraremos ambas rutas como correctas para la Entrega 1. Voy a modificar la Wiki para solucionar este problema, pero la última palabra siempre la tendrá el Enunciado, ya que la Wiki es solo una ayuda para guiarlos.

La regla general es:

- La aplicación web va en `~/Sites/EntregaN/`
- Los reportes van en `~/EntregaN/`

Saludos!
