### ISSUE TITLE
Consultas anteriores

### ISSUE THREAD

**Issue by ninifdr** [IIC2413/Syllabus-2019-2#160]
Hola! Tengo una duda, en la nueva entrega debo eliminar las consultas que hicimos para la entrega anterior o es acumulativo?
Gracias!

**Comment by nivek0o0** [comment]
Hola @ninifdr 

Todas las entregas son acumulativas. Como dice el primer párrafo del enunciado, el objetivo es refinar la aplicación. Por lo tanto, se deben añadir las nuevas funcionalidades y corregir las anteriores. 

Por ejemplo, para esta entrega yo separaría la navegación de las consultas, la búsqueda y el login.
