### ISSUE TITLE
Duda nested query en php

### ISSUE THREAD

**Issue by jfpena1** [IIC2413/Syllabus-2019-2#161]
Hola, si quiero hacer una consulta con dos consultas anidadas, en que cada una corresponde a una consulta sobre una db distinta, p.e query1 correspondiendo a db1 y query2 correspondiendo a db2, cuando quiero hacer la consulta anidada query3 que en su FROM llama a query1 as TABLA1, query2 as TABLA2, puedo incluirlas  query1 y  query2 directamente en el statement o debo hacer execute() primero ?

Nose si entiende mi duda, basicamente la duda es como es el formato para hacer consultas anidadas en php cuando son de bases de datos distintas.

Muchas Gracias.

**Comment by nivek0o0** [comment]
Tienes 2 opciones:

1. Haces un **execute** único de un gran _string_ que contenga las consultas anidadas. Para llamar a otra base de datos puedes usar la extensión **dblink** que tienen instalada (revisar las otras issues sobre ese módulo).

2. Haces consultas independientes a cada base de datos (múltiples **executes**) y luego ocupas el lenguaje de programación PHP para obtener el resultado que buscas. Por ejemplo, implementando tu propio JOIN o filtrando como desees.
