### ISSUE TITLE
Deadline entrega 3

### ISSUE THREAD

**Issue by aljara97** [IIC2413/Syllabus-2019-2#162]
Hola, dados los últimos hechos ocurridos en el acontecer nacional. Sumado a las distintas dificultades que esto implica para algunos grupos para reunirse e incluso poner atención en asuntos académicos, es posible correr nuevamente la fecha límite de la entrega 3 del proyecto?

De antemano muchas gracias

**Comment by clolate** [comment]
Si, por favor pueden dar información de que va a suceder? Yo hoy desperté sin luz, ha vuelto a ratos :(

**Comment by ciquezada** [comment]
Esta muy complicado todo y la luz tambien se ha vuelto un problema para avanzar la entrega

**Comment by quememo** [comment]
Favor anunciar si se mantiene la fecha o se cambia, la situación es complicada

**Comment by FaZorrilla** [comment]
Llego un mail:

"""
Estimados Estudiantes:

Estamos viviendo momentos muy difíciles en nuestro país y más que nunca es necesario que, como comunidad, nos mantengamos unidos y atentos para ayudar a quienes más lo requieran.

Sabemos que en estas condiciones es muy complejo poder concentrarse en las responsabilidades académicas y por lo mismo la Escuela ha decidido suspender todas las evaluaciones de los cursos de Ingeniería, durante la semana del 21 de octubre. Esto incluye interrogaciones, controles, entrega de tareas, proyectos, etc. Lo que queremos es que puedan preocuparse antes que nada de su propia seguridad y de las personas que los rodean.

Esto requerirá de esfuerzo y flexibilidad de parte de todos para poder reacomodar las evaluaciones en lo que queda de semestre. Cada profesor verá cuáles son los instrumentos y formas más apropiadas para recuperar estas evaluaciones resguardando los aprendizajes esperados en los cursos, pero entendiendo que estamos enfrentando una situación excepcional y compleja.

Cuídense mucho y recuerden contactarnos en caso de que requieran apoyo o necesiten compartir su situación particular.

Muchos saludos,

Dirección de Pregrado
Escuela de Ingeniería UC
"""

Me imagino que se analizara también con esto presente.

**Comment by nivek0o0** [comment]
Estimados, la entrega queda para el **Martes 20 de Octubre** a las **20:00 hrs**.

**Comment by aljara97** [comment]
Hola con respecto al mail que envió la dipre en el que dicen que las exigencias académicas de los cursos de ingeniería no debieran comenzar antes del 4 de noviembre, el plazo ya no es el 29 de octubre?

**Comment by VicenteMerino** [comment]
> Hola con respecto al mail que envió la dipre en el que dicen que las exigencias académicas de los cursos de ingeniería no debieran comenzar antes del 4 de noviembre, el plazo ya no es el 29 de octubre?

Tengo la misma duda. Gracias de antemano

**Comment by ciquezada** [comment]
También tengo esa duda

**Comment by juanreutter** [comment]
Hola, vamos a ver que hacemos hoy, pero efectivamente esta semana no hay nada academico (ni clases), asi que es un tema de cono recalendarizamos a futuro.
