### ISSUE TITLE
Duda Navegacion y busqueda

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#163]
Hola me preguntaba si me pueden explicar un poquito mas la diferencia entre navegacion y busqueda

navegacion seria como partir un busqueda general e ir refinandola con filtros?
busqueda seria como partir solo con unas barras de busqueda?

solo en busqueda los nombres deben ser clickeables?

creo que la manera en que describi navegacion tambien abarco la parte de busqueda. o no?

ayuda

**Comment by nivek0o0** [comment]
Hola,
### **Navegación** 
Es el primer requerimiento del enunciado. Consiste en poder ver todas las entidades e ir navegando a través de sus entidades asociadas haciendo click en hipervínculos. (_esto se deduce del 2do requerimiento, que es como una extensión del anterior_). Piénsalo como un grafo donde las entidades se conectan entre ellas. Dos entidades relacionadas deben poder navegarse en ambos sentidos. Se debería poder hacer la siguiente ruta Proyecto -> Recurso -> ONG -> Otro Recurso -> Otro proyecto.

Para mostrar todas las entidades como una lista pueden implementar en alguna barra de navegación las opciones para **Ver todos los proyectos**, **Ver todas las ONGs**, (_... y login, logout, etc_). Un botón en la página principal también es válido. 

Luego de hacer click, por ejemplo, en alguna ONG de la lista, puedes llevar al usuario a una página distinta donde se muestre toda la información de esa ONG _(de aquí se deduce que necesitarías 3 páginas distinta para mostrar la información de una entidad individual)_. El único detalle es que la lista de proyectos debe tener un pequeño filtro según el tipo.

**Búsqueda**: consiste en poder buscar según un determinado atributo (_causa_contaminante para el Recurso, nombre para los otros_), cualquiera de las 3 entidades principales. La forma más amigable de implementarlo es mediante un barra de búsqueda en alguna barra de navegación. También sirve un buscador en la homepage. Los resultados de esta búsqueda deben también tener un hipervínculo y entras nuevamente en la lógica de la navegación.
