### ISSUE TITLE
variables de sesión

### ISSUE THREAD

**Issue by kmhaller** [IIC2413/Syllabus-2019-2#164]
hola, no entiendo bien cómo puedo acceder desde otro archivo php a las variables de sesión ingresadas en un principio.
Al iniciar sesión, guardo diferentes variables del tipo $_SESSION['id'] por ejemplo, que es para guardar los valores de la sesión. Pero no he encontrado en internet cómo acceder después a esas variables. ¿Es con $_GET o la misma variable $_SESSION? ¿Hay una forma especifica de acceder a esas variables desde otro archivo?
saludos

**Comment by nivek0o0** [comment]
Hola @kmhaller, se acceden a ellas a través de la variable $_SESSION, que es global y accesible desde cualquier archivo. 
[Aquí](https://www.php.net/manual/es/function.session-start.php) está la documentación oficial y en internet está lleno de casos de uso.

**Comment by kmhaller** [comment]
Lo intenté, pero aun no me funciona. Después de hacer query = "codigo sql", prepare,  lo que trato de hacer es lo siguiente: 
$resul -> execute(array(':uid'=> $_SESSION['userID'], ':pid'=> $pid));
y no entiendo por qué no funciona ocupar la variable $_SESSION ahí. Si pongo un numero en su lugar, por ejemplo '100' sí funciona. ¿Cómo tengo que usarlo para que funcione?
gracias!

**Comment by aaguilarg** [comment]
la agregaste ```session_start();``` en tag de php al inicio? Tienes que hacerlo para poder usar $_SESSION

**Comment by kmhaller** [comment]
si, lo agregué!

**Comment by kmhaller** [comment]
Ahora funciona, gracias!!
