### ISSUE TITLE
[Entrega 3] - Datos con comilla simple ( ' ) en la bd.

### ISSUE THREAD

**Issue by AndresFaure** [IIC2413/Syllabus-2019-2#165]
Hola, estoy haciendo una consulta del estilo:

```
"SELECT * FROM proyectos WHERE nombre IN ({$str_nombres});"
```

Donde `$str_nombres` es un string de formato `"  'nombre1', 'nombre2', ..., 'nombrek' "` creado haciéndole `implode` a un `array` con nombres.
En el fondo, la idea de la consulta es dado un `array` con nombres de proyectos, buscar las filas correspondientes a esos proyectos en la bd.
Mi problema es que hay un proyecto llamado **The Chefs' Warehouse, Inc.**, que posee un comilla simple en su nombre (también pasa con **Sportsman's Warehouse Holdings, Inc.**). SQL interpreta esa comilla como el finaizador de un string, por lo que me devuelve un error.
Mi pregunta es: puedo editar la bd para eliminar esa comilla o debo buscar otra forma de programar lo que quiero?

**Comment by cmp831** [comment]
Hola, deben escapar el comilla simple usando algo similar a lo mencionado [acá](https://github.com/IIC2413/Syllabus-2019-2/issues/153#issuecomment-543426581).

**Comment by AndresFaure** [comment]
Aa ok. Gracias!
