### ISSUE TITLE
[Entrega 3] Socios y Ongs

### ISSUE THREAD

**Issue by conikuschel** [IIC2413/Syllabus-2019-2#166]
Los socios y ongs que se pueden registrar son solo los que están en la base de datos que nos dieron o se tienen que poder agregar otros?

Muchas gracias de antemano.

**Comment by nivek0o0** [comment]
Se deben poder agregar otros. Los de la base de datos deben estar ya registrados.

**Comment by ciquezada** [comment]
¿Entonces este es un requerimiento que se agrega al enunciado?
puesto que solo se menciona el poder logearse con alguna credencial existente

**Comment by nivek0o0** [comment]
Tienes razón, me confundí, lo siento.

No se menciona el **poder agregar nuevos usuarios**, asi que **no** es un requerimiento.

@conikuschel

**Comment by kmhaller** [comment]
No me quedo claro el registro de socios. Se supone que tienen que estar registrados de antemano con una contraseña cualquiera? Por favor si pueden aclarar este punto. 
Tendría más lógica que sólo los que están en la base de datos puedan crearse una cuenta con su nombre y apellido y elegir su propia contraseña, para poder ingresar.
saludos.

**Comment by nivek0o0** [comment]
No existe la funcionalidad de registro. 

Deben estar registrados de antemano con una contraseña cualquiera.

**Comment by kmhaller** [comment]
¿Las ongs también? gracias!
saludos

**Comment by nivek0o0** [comment]
Si
