### ISSUE TITLE
login como ong

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#168]
una ONG logeada puede ver solo sus propias movilizaciones?
las movilizaciones entonces son privadas y ocultas para cualquier otro usuario?

**Comment by nivek0o0** [comment]
Las movilizaciones no son privadas porque se pueden ver como usuario no logeado, y por lo tanto como usuario logeado también navegando por la página o utilizando el buscador. (suponiendo que al logearse se mantienen las funcionalidades de no logeado)

A lo que se refiere el item de Login es que una ONG pueda ver sus propias movilizaciones de una forma más directa, en una página de Perfil por ejemplo o en el homepage.
