### ISSUE TITLE
dblink_exec('INSERT INTO ....')

### ISSUE THREAD

**Issue by castrillini** [IIC2413/Syllabus-2019-2#170]
Hola, al escribir el comando SELECT dblink_exec('INSERT INTO foo VALUES(a, b ,c );'); me funciona todo perfecto si es que a, b y c son int o float. Sin embargo, si a,b o c es VARCHAR no me funciona. He probado de varias maneras, por ejemplo SELECT dblink_exec('INSERT INTO foo VALUES(a,b,"string";'); y no me funciona.

Aparte he intentado:
CREATE OR REPLACE FUNCTION probar()
RETURNS void AS $$
DECLARE
    tipo VARCHAR;
BEGIN	
	tipo='marcha';
	SELECT dblink_exec('INSERT INTO foo VALUES(123, tipo, 123876831);');
END
$$ language plpgsql;
pero tampoco me funciona :(

¿Cómo hago para insertar datos a una base de datos remota?

**Comment by cmp831** [comment]
Hola, 
Para escapar comillas simples con dblink, deben usar doble comillas simples como mencionado [acá](https://github.com/IIC2413/Syllabus-2019-2/issues/144#issuecomment-542466377)
Sobre el uso de las comillas en Postgres, te recomiendo revisar la documentación sobre las [comillas simples](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS) y [comillas dobles](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS)
