### ISSUE TITLE
No se logra insertar en tabla

### ISSUE THREAD

**Issue by jfpena1** [IIC2413/Syllabus-2019-2#171]
Hola, tengo el mismo problema que en la issue #153 respecto a insertar valores en tabla, pero no he podido solucionarlo con la solucion que muestran.

Mi codigo luce asi:
```
$query_mov = "INSERT INTO Movilizacion VALUES(:idmovilizacion, :presupuesto, :tipo, :idong, :idproyecto)";
    $result_mov = $db2 -> prepare($query_mov);
        
    $result_mov->bindValue(':idmovilizacion', $id_mov);
    $result_mov->bindValue(':presupuesto', $presupuesto_individual);
    $result_mov->bindValue(':tipo', $tipo_mov);
    $result_mov->bindValue(':idong', $idong);
    $result_mov->bindValue(':idproyecto', (int)$p[0]);
    $result_mov->execute();
```

El problema no es que tire error, sino que simplemente no inserta valores en la tabla ```Movilizacion```

Muchas gracias

**Comment by cmp831** [comment]
Hola,
Cuando no se ejecuta la consulta para insertar, significa es posible que existan problemas con el query. Pueden usar la función [`debugDumpParams()`](https://www.php.net/manual/en/pdostatement.debugdumpparams.php) para retorna el query usado, y revisar los parametros usados. Tengan en cuenta que esa función no retorna nada, y solo mustra la información en el stdout. Como ustedes no tienen acceso para ver eso, pueden usar algo similar a lo mensionado en este [stackoverflow](https://stackoverflow.com/a/25315378)
