### ISSUE TITLE
Bases desde servidores distintos

### ISSUE THREAD

**Issue by SergioGazali** [IIC2413/Syllabus-2019-2#172]
Hola!
Estoy tratando de hacer la conexión entre las dos bases de datos para procedimientos almacenados, usando dblink. Viendo otras issues entendí que están haciendo el dblink_connect ingresando el nombre y contraseña de la otra base de datos. Me imagino que esto significa que la tienen en el mismo servidor o no? Es posible conectarse con dblink a otro servidor? y es permitido tener las dos bases de datos en un mismo servidor? 
muchas gracias!

**Comment by nivek0o0** [comment]
Creo que tienes una leve confusión. El servidor que ocupamos para este curso (_ubicado en codd.ing.puc.cl_) es 1 solo. Lo que en realidad sucede es que cada grupo tiene un usuario dentro de ese servidor. (Como las cuentas de usuario de Windows). 

Por lo tanto, todas las bases de datos están **en el mismo servidor**. Esto implica que la conexión entre ellas sea tan sencilla como pasar el nombre de la DB y la contraseña de postgres del otro usuario, porque todo sucede dentro de la misma máquina.

Este tipo de funciones también permite conectarte a DB ubicadas en otros computadores (_en este caso otros servidores realmente_) muy lejanos, por ejemplo en China, especificando la dirección web de ese servidor, junto a todos los demás parámetros.

Para este proyecto, **está prohibido migrar todas las tabla a la DB de un solo grupo** para evitar implementar esta conexión múltiple. Lo dice el enunciado en la sección "Descripción de tareas a realizar", primer párrafo, segunda frase.
