### ISSUE TITLE
Desplegar información de proyectos (socios)

### ISSUE THREAD

**Issue by Witomi** [IIC2413/Syllabus-2019-2#173]
Hola!

Cuando tengo que desplegar toda la información de los proyectos, para el caso de socios,¿puedo dejar un texto que diga socios que al hacer click se despleguen todos los nombres? y si no, ¿Cómo debería desplegarlo? pues mostraría muchas filas pero solo con socios distintos..., quizás hay una forma de juntar los socios en una sola tupla pero la desconozco...

Gracias desde ya!

**Comment by nivek0o0** [comment]
Hola, 

Puedes implementarlo de la forma que tu consideres que se ve mejor y es más fácil de leer y corregir.

Una fila con los Socios separados por coma suena bien. Podrías hacer un loop que escriba 
`<td> Link Socio1 </td> <td> Link Socio2 </td> ...`
