### ISSUE TITLE
Nombre de ONG en Procedimiento Almacenado

### ISSUE THREAD

**Issue by ridiaz2** [IIC2413/Syllabus-2019-2#175]
¡Hola! Espero estén bien, y perdón por una issue tan cerca a la entrega D:

Tengo una duda relacionada con el item de Planificación. En este se menciona que las nuevas movilizaciones estarán organizadas por la ONG logeada, y que su nombre no se puede pedir nuevamente (se obtiene de la sesión). De esta forma, es posible obtener el nombre a través de _$\_SESSION_ con php, pero no estoy seguro de cómo poder obtenerla con procedimiento almacenado, y cómo hacer visible esto en el archivo .sql que debemos dejar para la entrega.

Con la frase:  
> *no puede pedir nuevamente su nombre*

entiendo que tampoco se puede entregar este dato como parámetro de la función.
Una idea podría ser redefinir la función para la ong logeada al intentar planificar, pero no creo que sea la solución. La otra forma sería agregarla con:

`$result -> execute( array(":nombre_ong" => $nombre_ong) );`

¿Esto se podría hacer?

¡Muchas gracias! Y perdón si estoy demasiado perdido con esta parte, o si esto ya fue respondido.

¡Saludos!

**Comment by nivek0o0** [comment]
Hola, disculpa la demora :disappointed: 

El enunciado dice que _La función debe recibir el Nombre de la Comuna y el Presupuesto Total_. Allí hay un error y falta el nombre de la ONG logeada.

Asi que sí, puedes ejecutar el procedimiento almacenado como mencionas.

**Comment by ridiaz2** [comment]
Ooooh, no hay problema! abrí la issue muy tarde jaja ¡muchas gracias! Después asumimos que el nombre de la ONG no se le pide al usuario, pero sí lo agregamos al llamar a la función, así que todo bien! Gracias de nuevo :D
