### ISSUE TITLE
problema con random en bucle

### ISSUE THREAD

**Issue by Deleon20** [IIC2413/Syllabus-2019-2#176]
Hola! Tengo un problema con un random en un bucle, básicamente cree un array que contiene "redes sociales" y "marcha", después use la función rand(0,1) para crear un valor aleatorio ($valor) del array. Al imprimir $valor en la pagina parece funcionar correctamente. Después pongo un if ($valor="redes sociales") y un elseif ($valor="marcha"), y solo entra el primer if y nunca al elseif.

Gracias por la ayuda!

**Comment by nivek0o0** [comment]
La comparación es con `==`

**Comment by Deleon20** [comment]
Gracias!
