### ISSUE TITLE
Permiso denegado, no puedo accerder a la base de datos de mi grupo.

### ISSUE THREAD

**Issue by fpaez7** [IIC2413/Syllabus-2019-2#18]
Al intentar hacer psql grupo 39 no me deja acceder a la base de datos.  Como puedo recuperar mi privilegio a conectarme??

`psql:FATAL:  permission denied for database "grupo39"`
`DETAIL:  User does not have CONNECT privilege.`

Probe [esto]([https://stackoverflow.com/questions/19302398/psql-permission-denied-for-database-dbname-user-does-not-have-connect-privi]) pero no entiendo que que es `qgis` en la respuesta mas votada.

**Comment by nivek0o0** [comment]
Hola @fpaez7 

Las bases de datos estarán bloqueadas mientras se realiza la corrección del último requisito de la primera Entrega.
