### ISSUE TITLE
Modificaron mi correccion de la entrega 2

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#180]
Hola, modificaron la nota que tenía en mi entrega 2 y me descontaron nota por consultas que sí estan por lo que ahora necesito recorregir.
Qué puedo hacer?

**Comment by nivek0o0** [comment]
Hola, ¿estás seguro que se modificó tu nota?

Estoy revisando el historial de versiones de la planilla y el 13 de octubre (día en que se publicaron las notas de la E2) tu corrección está idéntica a como está ahora.

![Captura de pantalla de 2019-12-01 13-14-14](https://user-images.githubusercontent.com/20782451/69914467-c4c41700-143c-11ea-9a39-55faf78b7eea.png)

Si aún no estás conforme, puedes mandar a recorregir por el formulario.

**Comment by ciquezada** [comment]
oh, perdon, y donde puedo encontrar el formulario?

**Comment by nivek0o0** [comment]
el link está en el aviso que mandé ayer
