### ISSUE TITLE
Foreing key

### ISSUE THREAD

**Issue by absoto4** [IIC2413/Syllabus-2019-2#19]
Hola, ¿pueden dar un ejemplo de cómo se pasa un modelo E/R que contenga una foreing key a un esquema relacional? Gracias! Pd: con foto se entiende mejor, gracias!

**Comment by nivek0o0** [comment]
Hola @absoto4 

Las llaves foráneas corresponden a una restricción de integridad que te impide referenciar a otra entidad si ella no existe. Esto ayuda a mantener la integridad de la BD. 

Lo que queremos que hagan para esta entrega es que puedan pasar desde el primer diagrama al segundo:

![Proyecto IIC3103](https://user-images.githubusercontent.com/20782451/63906174-ebf5ed00-c9e4-11e9-9cb7-aa5cbd733c98.png)

En el modelo relacional cada recuadro implicará una tabla en la base de datos, ya sea para almacenar entidades o relaciones. La dificultad está en encontrar las tablas necesarias para modelar correctamente un esquema con distintos tipos de cardinalidades (1:1, 1:n y n:m), tal vez con relaciones ternarias y otros tipos de particularidades.

En mi ejemplo, sabemos que cada producto es producido por una única compañía, o en otras palabras, si tengo el producto, debería poder llegar directamente a la compañía. Para satisfacer lo anterior es que en la tabla Productos agrego una llave foránea que corresponde a alguna llave primaria de una Compañía.

Espero haber solucionado tu duda, de lo contrario no dudes en continuar con esta issue!

**Comment by Tngarrido** [comment]
Hola @nivek0o0 
Yo en la clase del miércoles había entendido que para pasar a un esquema relacional, solo debíamos transformar cada relación a una tabla, o ¿ ocupar foreing key es otra forma de representar lo mismo ?
Saludos.

**Comment by nivek0o0** [comment]
Hola @Tngarrido 

Tienes razón, para pasar a un esquema relacional lo que se hace principalmente es modelar cada **entidad** como una tabla y tal vez cada **relación** (dependerá de su cardinalidad).

Además de eso, nosotros les pedimos que implementen restricciones de integridad como _primary keys_ y _foreing keys_. Estas restricciones son **independientes**, pueden estar o no estar, pero si se desea una base íntegra y coherente es altamente recomendable utilizarlas.

**Comment by juanreutter** [comment]
Agrego: Vimos algunas cosas en los diagramas que fuerzan a que existan llaves foráneas, como por ejemplo las entidades débiles (que no existen si no está la entidad fuerte con que se relacionan). 

Pero como dice @nivek0o0, incluso si el diagrama E/R no exige llaves foráneas, es una buena práctica colocarlas en todas las tablas de relaciones.

**Comment by absoto4** [comment]
Hola @nivek0o0, gracias por tu explicación! Y en cuanto a cómo expreso una foreign key en un esquema relacional como los vistos en clases, cómo se hace?  En tu ejemplo:

Compañía (id_compañía: int, nombre: text, latitud: float)
Producto (id_producto: int, nombre: text, precio: float, id_compañía: int)

pero cómo expreso que id_compañía es una llave foránea en Producto?

**Comment by nivek0o0** [comment]
@absoto4 

Puedes hacerlo de la forma que tu quieras, siempre que se entienda.

Por ejemplo, podrías destacarla con otro color o agregar la sigla FK luego del tipo de dato.
Producto (id_producto: int PK, nombre: text, precio: float, id_compañía: int FK)
