### ISSUE TITLE
"Hellow world"

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#190]
Corrí la api de Hellow wolrd y ingrese al link y funciono, pero ahora corro la api de la ayudantia de API y me aparece siempre Hellow World al ingresar al link. A que se puede deber?

**Comment by cmp831** [comment]
Hola, tu problema probablemente es que tu servidor antiguo de `Hello World` sigue corriendo, y todos los traficos son recibidos por el servidor antiguo en vez del servidor de la ayudantia de APIs. 

En windows, a cambio de otros sistemas operativos, al ejecutar el segundo server de Flask en el mismo puerto no te entrega un error en la consola. Puedes conocer más leyendo la documentación de [Microsoft](https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse?redirectedfrom=MSDN)
