### ISSUE TITLE
AttributeError: 'Cursor' object has no attribute 'pretty'

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#195]
Me aparece este error cuando ejecuto mi comando y llevo mucho timepo tratando de arreglarlo a que se puede deber? 
![image](https://user-images.githubusercontent.com/48294819/70098624-51243480-160b-11ea-81ac-528438126930.png)

**Comment by nivek0o0** [comment]
Estimado,
este es el primer resultado al googlear el error:
![20191203_210923](https://user-images.githubusercontent.com/20782451/70100673-35bc2800-1611-11ea-963f-08903c6d4d6f.jpg)

Te sugiero poner un poco más de esfuerzo en la búsqueda de la solución de los errores y recurrir al foro cuando ya no queden más opciones. De lo contrario dejaremos de responder este tipo de preguntas.
