### ISSUE TITLE
Fecha entrega 1

### ISSUE THREAD

**Issue by absoto4** [IIC2413/Syllabus-2019-2#2]
Hola, en el programa dice que la entrega 1 es para el lunes 26 de Agosto, pero el enunciado dice que es para el viernes 23 ¿Pueden aclarar esto por favor?

**Comment by juanreutter** [comment]
Claro, en el programa hablamos de que podía sufrir cambios. La verdad es que re-evaluamos, y como era tan simple lo que hay que hacer, preferimos pedirles que lo hagan durante la semana, así si hubiese algún problema podemos resolverlo el fin de semana sin alterar el resto de la programación.
