### ISSUE TITLE
Slides semana4

### ISSUE THREAD

**Issue by aaguilarg** [IIC2413/Syllabus-2019-2#21]
Traté de abrir las slides de las clases de la semana 4, ```09 - Dependencias.pdf``` y ```10 - Nulos y Outer Joins.pdf```, en mi computador y en github, y no puedo abrirlos. Al intentar abrirlos en mi computador, dice que no es un tipo de archivo admitido o estan dañados.

Es esto un error mío? O efectivamente los archivos estan dañados?

Gracias de antemano!

**Comment by juanreutter** [comment]
Gracias! 
Ahí deberían estar OK.
