### ISSUE TITLE
Postman URL vs PATH

### ISSUE THREAD

**Issue by Kitaps** [IIC2413/Syllabus-2019-2#214]
Hola, 

en el feedback que se nos dió de la entrega 4 sale que: 

> Descuento de 3 decimas por usar PATH en G2.1, G2.2 y G2.3, ya que en la issues se indicó que debía ser URL .

A que se refiere con eso? El problema es que lo tenemos con localhost? Es un problema del archivo de PostmanCollections?

De antemano muchas gracias

**Comment by nivek0o0** [comment]
Hola, ese descuento ya no existe más. Lo eliminé porque el enunciado no era claro al respecto.

Era porque esperábamos que hicieran `/messages/project-search?nombre=MiProyecto`
en vez de `/messages/project-search/MiProyecto`

**Comment by Kitaps** [comment]
Ahh ok, gracias por la pronta respuesta. 

Sorry la molestia pero, cual es la diferencia entre hacerlo de una o la otra forma? O donde puedo averiguar más? Que estuve buscando en google sin exito.

**Comment by nivek0o0** [comment]
la primera forma se denomina pasar **query parameters** al final de la URL
la segunda forma intenta respetar las convenciones de REST que hacen que una api sea **RESTful**.

**Comment by Kitaps** [comment]
gracias
