### ISSUE TITLE
Problema conexion con psql

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2413/Syllabus-2019-2#22]
Estoy tratando de conectar mi pagina web con psql y no pude hacerlo, llevo harto rato tratando de arreglar el error, pero no entiendo en que fallo.

Estoy haciendo esto para conectarme:
 `$db_connect = pg_connect("host=".$dbServerName." dbname=".$dbName." user=".$dbUserName." password=".$dbPassword);`

pero me lanza este error, lo busque en internet pero no pude solucionarlo

![image](https://user-images.githubusercontent.com/42476356/64272608-b7ff5800-cf0d-11e9-9c21-2ed257d2d522.png)

**Comment by cmp831** [comment]
Hola, el servidor de bases de datos que le otorgamos no acepta conexiones remotas. La idea del proyecto es que ustedes suban sus páginas de PHP en el servidor, de esa manera puede acceder a Postgres de manera local. En esta [sección](https://github.com/IIC2413/Syllabus-2019-2/wiki/Tutorial-Servidor#organizaci%C3%B3n-del-servidor-y-url) de la wiki explica donde deben subir sus páginas al servidor, y como accederemos desde un navegador. 
Se realizará una ayudantía este viernes que se enfocará en PHP y el proyecto. 

PD: Felicitaciones por la instalación de PHP en su computador, el servidor que les damos está para que no tengan que sufrir la instalación de PHP.

**Comment by lfuenzalida2** [comment]
Graciaas
