### ISSUE TITLE
Conectar el PHP con el servidor

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2413/Syllabus-2019-2#23]
Estuve intentando de abrir mis archivos PHP en el servidor y no fui capaz, no se si lo estoy haciendo mal yo o hay algun problema.
Subi todos mis archivos necesarios para el PHP al servidor (por SCP) y no soy capaz de abrirlo, intente en mi navegador (Google Chrome) abrir la pagina con el siguiente link

http://codd.ing.puc.cl/home/grupo24/Sites/Entrega2/index.php

Con el cual según tengo entendido debería ejecutar el archivo index.php, pero me sale lo siguiente:

![image](https://user-images.githubusercontent.com/42476356/64292221-e003b100-cf37-11e9-80a7-11d626d9f120.png)

Que puedo hacer para arreglarlo?

**Comment by nivek0o0** [comment]
Hola @lfuenzalida2 

la ruta correcta es `http://codd.ing.puc.cl/~grupo24/Entrega2/index.php`

Según la wiki, la ruta /home/ se abrevia con ~. Además, la carpeta Sites se oculta.
