### ISSUE TITLE
Creación tablas

### ISSUE THREAD

**Issue by jfpena1** [IIC2413/Syllabus-2019-2#24]
Hola, quería saber si para subir los datos es necesario modificar las tablas con comandos SQL (para lograr BCNF) o es posible modificar los datos con python y luego subir esas nuevas tablas ya modificadas.

Muchas gracias

**Comment by juanreutter** [comment]
Las tablas (el esquema relacional) deberia quedar listo antes, cuando las crees con CREATE TABLE. Luego de eso esta el desafio de poblarlas con los datos que te dimos. Para eso, puedes manupular los csv con python, o subir todo a una tabla temporal y manipular con SQL. Nos da igual.

**Comment by jfpena1** [comment]
gracias!
