### ISSUE TITLE
Duda relacion debil

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#25]
Las relaciones débiles solo aparecen cuando tenemos una flecha unidireccional o bidireccional? o cuando no tenemos flecha y solo linea si puede ser débil?

**Comment by nivek0o0** [comment]
> Las relaciones débiles solo aparecen cuando tenemos una flecha unidireccional o bidireccional?

Sí, las entidades débiles se relacionan con otra entidad principal con cardinalidad 1:N (flecha unidireccional). En este [link](https://www.dataprix.com/es/217-entidades-debiles) se explica muy bien.

**Comment by valeeeriquelme** [comment]
Todas las entidades que se encuentren en una relación de 1:N serán entidades débiles? Por ejemplo en el caso de Proyectos y Ubicación, un proyecto puede tener solo una ubicación pero en una ubicación puede haber más de un poyecto. En este caso Proyectos sería una entidad débil?
