### ISSUE TITLE
Duda Relacion sin key

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#26]
Puede existir una relacion sin key, como por ejemplo en el proyecto que hay muchas asociaciones de Recursos ambientales y ONGs, de los cuales cada ONG puede estar asociada a mucho resursos y cada recurso puede estar asociado a muchas ONGs. O en este caso se considera a la tupla como llave?

**Comment by nivek0o0** [comment]
En la vida real siempre pueden existir relaciones sin llave primaria, pero esto conlleva el riesgo de que el usuario de tu BD ingrese datos repetidos y debilite la consistencia de tu base.

En este proyecto, **les exigimos** que utilicen llaves primarias y foráneas, así que tendrán que pensar cómo modelar dicha relación _muchos a muchos_ y utilizar llave primaria en su solución.

Si no he resueto tu inquietud, no dudes en continuar esta discusión!

**Comment by jalliende** [comment]
pero si la tupla es la llave entonce no se va a permitir valores repetidos? estaría bien esa solución?

**Comment by nivek0o0** [comment]
A qué tupla te refieres? Podrías poner un ejemplo?

**Comment by jalliende** [comment]
me refiero a que ambas columnas de la realcion sean llaves:
por ejemplo tengo la relación:
 ONG | Recurso
     1   |     1
     1   |     2 
     2   |     1 

ya que puede pasar que la ong 1 y 2 esten relacionadas a recurso 1 y la ong 1 tambien puede estar relacionada a los recursos 1 y 2. Aca la llave es (ong, Recurso)?

**Comment by nivek0o0** [comment]
Así es, la llave primaria de una tabla intermedia corresponde a las llaves primarias de las entidades relacionadas.
