### ISSUE TITLE
Base de datos Proyectos operados por multinacionales y Base de datos ONGs

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#27]
En la entrega 1 señala que debemos guardar solo el nombre del proyecto (enunciado par), pero en la base de datos se nos entregan mucha más información. Que hacemos con el resto de la información?

Ademas con respecto a esa base de datos y a las de ONGs no existe ningún valor nulo (NA), que se hace con ellas? se dejan como están? y el trabajo es en la de Movilizaciones y Recursos?

**Comment by nivek0o0** [comment]
Lo ideal es que guarden **solo los atributos** que su enunciado par o impar les indicaba.

Respecto a los valores nulos, la explicación es que esta información era manejada por personas distintas que representaban los nulos de distinta manera (guiones, NA, etc). Su trabajo es normalizar estas discrepancias, trabajando los datos como deseen. Pero ojo, deberían eliminar todos los nulos con un modelo adecuado.
