### ISSUE TITLE
Modelo E/R, IsA

### ISSUE THREAD

**Issue by castrillini** [IIC2413/Syllabus-2019-2#28]
Mi modelo E/R lo terminé la anterior semana. Ahora, observando los datos subidos el lunes 2 y con la materia de esta semana, me doy cuenta que debería añadir una relación IsA en mi modelo E/R. ¿Debo actualizar mi modelo E/R?

**Comment by nivek0o0** [comment]
Claro, debes actualizar tu modelo para que refleje de la mejor forma posible la situación que se desea modelar. De hecho, en la sección 2.2 del enunciado se indica que el modelo E/R se puede refinar en cualquier momento.

Saludos!
