### ISSUE TITLE
Comas (,) en los datos de csv

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#29]
Se puede asumir que no hay comas (,) en los valores excepto en las ONGs? o tenemos que ponerles "comillas" a todos los textos para asegurarnos de no poner alguna coma (,) de más?

**Comment by nivek0o0** [comment]
Los valores que corresponden a texto (por lo que podrían tener comas), ya vienen encerrados entre "comillas".  Los que no están encerrados entre comillas es porque nunca tendrán comas.
