### ISSUE TITLE
Grupos pares e impares

### ISSUE THREAD

**Issue by FloValdes** [IIC2413/Syllabus-2019-2#3]
Hola, cuando se junte un equipo par e impar será al azar? Si no lo es y podemos elegir, qué podemos hacer si teníamos un grupo de 4 pero los dos grupos quedamos en grupos pares? Podemos cambiarnos ahora? Después?

Gracias.

**Comment by nivek0o0** [comment]
@FloValdes 

Lo ideal hubiese sido avisar con anticipación a la publicación de los grupos. Pero lo que podemos hacer ahora es que las parejas que quieran cambiar de paridad se consigan a otro grupo que esté dispuesto. Luego me avisan por correo para hacer el intercambio y ustedes se encargan de pasarse los servidores. También avisarme con qué grupo quieren ser para las entregas futuras. 

Saludos
