### ISSUE TITLE
Duración manifestación RR.SS. en meses o días (?)

### ISSUE THREAD

**Issue by aaguilarg** [IIC2413/Syllabus-2019-2#30]
Hola, 

En el enunciado de la entrega 1, dice que debemos guardar la duración de las movilizaciones de redes sociales en meses, sin embargo, en los datos entregados, estos se dan en días. Por lo que, podríamos pasarlos a meses pero o quedarían en floats (lo que complica su operación en las consultas por movilizaciones vigentes) o en enteros (lo que modificaría su valor real).
Es por ello que me nace la duda de si es necesario transformar ese valor a meses, o podemos dejarlos en días?

Gracias

**Comment by nivek0o0** [comment]
Hola @aaguilarg 

no nos interesa la implementación que escojas para almacenar ese atributo. En otras palabras, no estará incorrecto si el enunciado decía meses pero decides guardarla en días.

Lo que **sí importa** es que entreguen la respuesta correcta a las consultas que les pediremos. Por ejemplo, 

- Pregunta: `muestre en meses la duración de la marcha más larga`
- Respuesta correcta: `5,43 meses`

Y si no se especifica la unidad temporal, deben entregarla ustedes:
- Pregunta: `muestre la duración de la marcha más larga`
- Respuesta correcta: `162,9 días`

Respecto a los meses como floats, no deberían presentar ninguna complicación para realizar consultas. Por ejemplo, si quisieras saber si una marcha ya terminó, calculas la diferencia entre su fecha de inicio y la fecha actual y comparas el resultado con tu duración decimal.
