### ISSUE TITLE
Importar Datos

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#31]
Hola
he intentado importar los datos a un tabla como nos indican [acá](https://stackoverflow.com/questions/2987433/how-to-import-csv-file-data-into-a-postgresql-table), tengo subido un archivo Socios.csv en el servidor ("grupoxx/Entrega2/Datos/Socios.csv"), pero cuando entro en "psql grupoxx" quedo perdido con los path que debo utilizar, he intentado permutaciones del path, pero siempre me sale "No such file or directory", me podrían decir como debería ir el path en nuestro caso. Saludos
![image](https://user-images.githubusercontent.com/42189869/64311430-1e1dc680-cf72-11e9-9570-d5180a19958e.png)

**Comment by cmp831** [comment]
Como se indicó en el issue #14, el comando puede funcionar con paths relativos, eso quiere decir que si haces cambios de directorios `cd` a donde se encuentra `Socio.csv`, basta ingresar `\copy NOMBRE_TABLA from 'Socios.csv' delimiter ',' csv header`. 

También se puede usar path absoluto, puedes ver el path absoluto en que te encuentras con el comando `pwd`, como verás, el path absoluto para tu archivo será `home/grupoxx/Entrega2/Datos/Socios.csv`. Entonces para importar la tabla, puedes ejecutar `psql` desde cualquier directorio, y ejecutar el comando `\copy NOMBRE_TABLA from '/home/grupoxx/Entrega2/Datos/Socios.csv' delimiter ',' csv header`.
