### ISSUE TITLE
Duda creacion id

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#32]
Cuando no tengo ningún candidato a llave me sirve crear un atributo id? y de ser asi para crearlo es necesario añadirlo manualmente en los csv correspondientes? Gracias.

**Comment by nivek0o0** [comment]
Estás en lo correcto, pueden agregar todos los ID's que consideren necesarios. Sólo tienen que asegurarse que las referencias entre las distintas entidades queden consistentes.
