### ISSUE TITLE
Comparacion de fechas sql

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#33]
Como se pueden comparar fechas en sql en caso de que esten en el formato DD/MM/AAAA, ya que por ejemplo si pongo a>b tiene sentido, pero como podemos filtrar por mes, dia o año? o es necesario escribirlas en otro formato?

**Comment by nivek0o0** [comment]
Postgresql tiene muchas funciones para el manejo de fechas, entre ellas extraer el dia, mes, año, etc. Estas se explican en su [documentación](https://www.postgresql.org/docs/9.1/functions-datetime.html)

Ahora bien, para importar las fechas a una tabla tienes muchas opciones, puedes importarlas como varchar y luego transformarlas a date, manipularlas antes e importarlas directo a una columna date, incluso apostaria a que si ese formato DD/MM/AAAA lo importas en un atributo de tipo Date igual lo reconoce correctamente, aunque debes tener cuidado con que no confunda los días y los meses. 

Mi sugerencia es que intentes estas opciones. Echando a perder se aprende!

**Comment by mihenriquez** [comment]
Hola! Yo también he tenido muchos problemas, he probado todo lo que he encontrado googleando pero no he podido comparar fechas. Mi columna es tipo DATE y los inputs los recibo como date también. Probe recibiendo los inputs como text y después pasarlos pero nada. Lo único que me ha funcionado es comparar mi columna con un input metido a manod desde el código, de la forma: `RecAmb.fecha >= date('2010-10-10')` Porfa ayudenmee

**Comment by cmp831** [comment]
@mihenriquez Hola, puedes especificar de donde estas mandando el input? Te recomiendo hacer `echo` al variable que estas tomando como input, para saber exactamente el valor que estas mandando en la consulta SQL.

**Comment by imunoz3** [comment]
El input lo recibimos en el index como text (también probamos recibiéndolo como date) Y después en el archivo php de la consulta, recibimos los input igual que en la ayudantía. El tema es, cuando hacemos la cosnulta como string en el query, no se están comparando las fechas correctamente. Tenemos las fechas en las tablas como YYYY-MM-DD.
<img width="566" alt="Captura de Pantalla 2019-09-11 a la(s) 17 36 16" src="https://user-images.githubusercontent.com/30962736/64733243-bf4cd580-d4ba-11e9-8314-a56331031032.png">

**Comment by cmp831** [comment]
@imunoz3 No veo problemas en la consulta en si. Si ejecutan la consulta directamente en la consola usando psql, les retorna el resultado esperado? De ser así, el error debiese ser `$inferior` y `$superior`, por lo que les recomiendo hacer un echo de esos variables en la página de consultas.
