### ISSUE TITLE
Modelo E/R Entrega 2

### ISSUE THREAD

**Issue by sofiadelano** [IIC2413/Syllabus-2019-2#35]
Hola! El modelo de Entidad/Relación que debemos crear para la entrega 2 debe ser con las tablas que hicimos para la Entrega 1, o con las tablas una vez que cumplan ser un modelo en BCNF?

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola @sofiadelano 

Debe ser el modelo normalizado, sin nulos, sin pérdida de información, con las relaciones y cardinalidades correctas entre las entidades.

Y el esquema relacional debe crearse a partir de este modelo E/R final.
