### ISSUE TITLE
Modelo E/R

### ISSUE THREAD

**Issue by emena97** [IIC2413/Syllabus-2019-2#36]
Hola, dentro de los datos que nos pasaron hay varios atributos que no son necesarios (para esta entrega) para realizar las consultas correspondientes, debemos incluirlos igual en nuestro modelo E/R?

**Comment by nivek0o0** [comment]
Hola @emena97 

La idea es que utilicen solo los datos que su enunciado de la E1 les indicaba.

**Comment by emena97** [comment]
Osea solo pongo en el esque E/R los atributos que en el enunciado de la E1 decia que 'interesaba almacenar'? es que hay algunos que no lo dice explicitamente pero despues los necesito para las consultas (como el proyecto al q esta asociado un recurso)

**Comment by nivek0o0** [comment]
> Osea solo pongo en el esque E/R los atributos que en el enunciado de la E1 decia que 'interesaba almacenar'?
Sí

Pero ojo, el proyecto no es un atributo de un Recurso, es una relación entre 2 entidades. Si lo pusieras como atributo estaría malo.

**Comment by emena97** [comment]
Buenisimo.

Y entonces tendria una tabla por cada entidad y una tabla por cada relación cierto?

**Comment by nivek0o0** [comment]
Lo primero que dices es cierto, pero lo segundo no siempre, ya que dependerá de la cardinalidad de la relación.

**Comment by emena97** [comment]
Y en el caso de las movilizaciones por ejemplo, dado que la ONG y el proyecto son relaciones, que podria utilizar como key en esa tabla? ya que los factores que la diferencian son estos.

Y en que caso no hay una tabla dependiendo de la cardinalidad?

**Comment by nivek0o0** [comment]
> Y en el caso de las movilizaciones por ejemplo, dado que la ONG y el proyecto son relaciones, que podria utilizar como key en esa tabla? ya que los factores que la diferencian son estos.

Estás equivocado, el proyecto y la ONG no diferencian una movilización, puesto que una ONG puede auspiciar muchas movilizaciones para el mismo proyecto. Si no encuentras un conjunto de atributos que identifiquen inequívocamente a una entidad (_primary key_), tienes que evaluar si conviene asignarles un ID.

> Y en que caso no hay una tabla dependiendo de la cardinalidad?

- Si la cardinalidad es N:M estamos claros de que es necesario una tabla intermedia, cierto? De lo contrario, habría que colocar los IDs de la entidad relacionada cada uno en una columna o bien todos juntos, lo cual estaría pésimo y no quedaría normalizado.

- Si la cardinalidad es 1:N, la existencia de la tabla intermedia dependerá de los valores que pueda tomar N. 
Si N > 0, podemos prescindir de la tabla intermedia y simplemente utilizar una llave foránea en la entidad del lado de "N".
Si N puede ser 0, es decir, una entidad del lado del "1" puede estar relacionado con ninguna, entonces la llave foránea sería NULL y eso es un problema. En este caso conviene utilizar una tabla intermedia.

Por ejemplo, si un Proyecto se relaciona con varias Tareas, y una Tarea pertenece únicamente a un Proyecto (card 1:N), la forma correcta de modelar esto sería:

1. Si un Proyecto debe tener al menos 1 tarea:
Proyecto(ID: int PK, nombre: text, ...)
Tarea(ID: int PK, descripción: text, ..., proyectoID: int FK)

2. Si un proyecto puede tener 0 tareas:
Proyecto(ID: int PK, nombre: text, ...)
P-T(proyectoID: int FK PK, tareaID: int FK)
Tarea(ID: int PK, descripción: text, ...)
