### ISSUE TITLE
Duda llaves foraneas

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#37]
Las tablas que son IsA (la que heredan) necesitan llaves foráneas o no es necesario?

**Comment by nivek0o0** [comment]
_Por poner un ejemplo, supongamos que Camioneta hereda de Automóvil._

Sí, las llaves de las entidades que heredan son tanto primarias como foráneas. 
¿Por qué?

- Primarias porque no pueden estar repetidas en la tabla Camioneta.
- Foráneas porque no puede existir una Camioneta sin que exista como Automóvil.

**Comment by mjespinoza** [comment]
Holaa, tengo una duda con respecto a esto mismo, las entidades heredan la llave primaria de su “padre” como llave foránea o como llave primaria? Gracias de antemano!!

**Comment by arpincheira** [comment]
Como llave foránea, debido a que puede existir el caso en que más de una entidad herede de un mismo padre
