### ISSUE TITLE
Enunciado Impares: 'Recurso vigente'

### ISSUE THREAD

**Issue by mihenriquez** [IIC2413/Syllabus-2019-2#39]
Hola, tengo la duda sobre a que se refiere la consulta 4 de los impares cuando dice 'recurso vigente', es uno en tramitación, aprobado o rechazado? 

Gracias!

**Comment by nivek0o0** [comment]
Hola @mihenriquez 
Recurso vigente significa **en trámite** o **aprobado**.

**Comment by MGilB** [comment]
Se refieren a la región de tramitación o a la región donde está el proyecto?

**Comment by nivek0o0** [comment]
@MGilB Puedes hacer una issue nueva para responderte esto?
