### ISSUE TITLE
Relaciones de esquema Entrega 1

### ISSUE THREAD

**Issue by jfpena1** [IIC2413/Syllabus-2019-2#4]
Hola, respecto al esquema que se pide para los grupos PARES, se puede asumir que los nombres de los proyectos son únicos? o si no es el caso, asumir quw tienen un id identificador? 
Muchas Gracias, Julio.

**Comment by jfpena1** [comment]
También me surge la misma duda respecto a los socios. Quizás en ese caso podría usarse una llave doble con nombre y nacionalidad pero quizás es más útil y fácil con un  id. Gracias

**Comment by arpincheira** [comment]
Hola, con respecto a tu primera duda, efectivamente dentro del enunciado no aparece explícitamente que el nombre de los proyectos son únicos, por lo que, a menos de que justifiques un motivo por el cual pueden ser únicos, lo ideal sería no considerarlo así.

Con respecto a tu segunda duda ocurre lo mismo, por lo que tampoco es muy recomendable hacerlo con una llave doble con nombre y nacionalidad.

Es por esto que se deja a tu criterio encontrar una solución a estos problemas, pero ten cuidado con las consideraciones escritas anteriormente. De todos modos, recuerda  que un ID se suele usar cuando es muy difícil identificar inequívocamente una entidad.

Mucha suerte con la entrega.
