### ISSUE TITLE
Entrega 2 - Datos

### ISSUE THREAD

**Issue by nucontreras** [IIC2413/Syllabus-2019-2#40]
Como las bases de datos asumen inglés, ¿deberíamos sacar las ñ's?, si es así, ¿las cambiamos por n's?.

**Comment by nivek0o0** [comment]
Hola @nucontreras 

Postgresql tiene soporte para una infinidad de codificaciones distintas. No deberías tener ningún problema importando datos con 'ñ'.

**Comment by nucontreras** [comment]
Muchas gracias!
