### ISSUE TITLE
Calendario Programa

### ISSUE THREAD

**Issue by quememo** [IIC2413/Syllabus-2019-2#41]
Las fechas que aparecen en el programa de curso respecto a las entregas 3, 4 y 5 del proyecto están correctas? Me surge la duda ya que ninguna ha coincidido con el verdadero plazo y esto afecta a la planificación de los estudiantes, gracias de antemano.

**Comment by juanreutter** [comment]
Me encantaría decirte que si, pero no tengo como saber: la planificación del curso es dinámica (si a principio de semestre conocieramos todo lo que va pasar y cuando va a pasar, no tendría mucha gracia el curso, ¿o si? sería como ver una película nada más). 

Lo que si podemos hacer es volver a subir el programa con las nuevas fechas que manejamos ahora, que deberían ser más realistas que las anteriores (pero no puedo garantizar que sean las correctas).
