### ISSUE TITLE
levantar web ayudantía

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#42]
Hola
Estoy tratando de levantar la pagina como se explico en ayudantía
![image](https://user-images.githubusercontent.com/42189869/64503401-3dce2b00-d2a1-11e9-984d-c3838481aa30.png)
subí la carpeta app en la ruta "grupo79@codd.ing.puc.cl:/home/grupo79/Ayudantia", pero creo que no tome atención de como hacer para levantar la conexión del sitio web, probé ejecutando dentro de app el comando en la terminal "php config/conexio.php"  y luego ingresando la ruta "http://codd.ing.puc.cl/home/grupo79/Ayudantia/app/index.php" pero no me resulta :/
Saludos

**Comment by cmp831** [comment]
Hola, el servidor tiene instalado Apache, cual "sirve" todos los archivos que se encuentran en las rutas y sub rutas de `home/grupoXX/Sites`. Por lo tanto, para poder ver el contenido de las páginas PHP, siguiendo tu ejemplo, debes subir la carpeta a `home/grupo79/Sites/Ayudantia`. En este caso, la estructura de archivos será algo así:
```
├── home
    ├── grupo79
        ├── Sites
            ├── Ayudantia
                ├── app
                    ├── index.php
                    ⋮
```
Como sale en la diapositiva, debes acceder a la página omitiendo `home` y `Sites` de la ruta de tu archivo. Por lo cual el URL para este ejemplo será `http://codd.ing.puc.cl/~grupo79/Ayudantia/app/index.php`. 
Tampoco es necesario ejecutar comandos para ver la página, Apache se encargará de buscar tu página en base del URL ingresado.

**Comment by Tngarrido** [comment]
gracias @cmp831
