### ISSUE TITLE
Sobre transformar desde E/R a esquema relacional (recordatorio)

### ISSUE THREAD

**Issue by juanreutter** [IIC2413/Syllabus-2019-2#43]
Si tenemos dos entidades, A (con atributo llave ka) y B (con atributo llave kb), y estas están conectadas con una relación R, la forma en que pasamos esto a tablas depende de la naturaleza de esta relación: 

- Si la relación es de varios a varios (es decir, se dibuja sin flecha), entonces creo que queda bien claro que tienemos que generar tres tablas: una para la entidad A con llave ka, otra para la entidad B con llave kb y otra para la relación R. Esta última va a tener como atributos ka y kb (además de los atributos propios de R), y su llave va a ser (ka,kb). 

- Si la relacion es de varios a uno (es decir, se dibuja como A - [R] -> B)  entonces depende. Recordemos que en este caso cada entidad A va a estar relacionada con a lo más una entidad B.  
-- ¿es cierto que cada entidad de A va a estar obligadamente relacionada siempre con una de B? Entonces podemos prescindir de la tabla para R, y simplemente agregamos kb a los atributos de la tabla para A, para indicar la entidad de B con que la entidad de A está relacionada. 
-- ¿pueden haber atributos de A que no están relacionados con B mediante R? Entonces yo recomiendo poner una tabla para R igual, y la razón es la siguiente. Si en este caso hacemos lo que puse arriba (agregar kb a la tabla de A), en aquellas tuplas que representan entidades que no están relacionados con nadie de B, vamos a tener que dejar el atributo kb nulo. Y ya sabemos lo peligroso que puede ser eso. 

- Si la relación es de uno a uno (se dibuja como A <- [R] -> B), y encontramos que siempre alguna de las entidades que va a estar obligadamente relacionada con una de la otra, podemos prescindir nuevamente de la tabla para R. Pero si pueden haber entidades de A que no estén relacionadas, y entidades de B que no estén relacionadas, entonces conviene hacer la tabla para R.

**Comment by nivek0o0** [comment]
Leer también la #36

**Comment by jalliende** [comment]
En el primer caso es necesario que la relacion R tenga como llaves foraneas kb y ka, o no es necesario?

**Comment by juanreutter** [comment]
@jalliende: nunca es bueno pensar en esos términos absolutos, asi que mejor veamos las dos opciones. Supón que no pones las llaves foráneas. ¿Qué podría pasar? que la relación R tenga alguna tupla cuyo valor de ka o de kb (o de ambas) no se encuentre en la tabla para A o en la para B.  Como regla general vamos a tratar de evitar esto, por que significaría que estamos modelando relaciones de entidades cuyos datos no tenemos. Pero claro que pueden haber escenarios en los que eso es bueno.

**Comment by ninifdr** [comment]
@juanreutter en ese último caso ka y kb serían llaves primarias y foráneas al mismo tiempo en la relación R? Porque además de condicionar la existencia queremos que no se repitan las tuplas dentro de la relación.

**Comment by juanreutter** [comment]
Claro, en la relación R vas a tener: 
- la llave primaria es (ka,kb), las dos juntas. 
- ka en R apunta a ka en A (lláve foránea que dice que los ka en R deben de estar en A)
- kb en R apunta a kb en B

**Comment by ninifdr** [comment]
Ya perfecto, era como pensábamos!
