### ISSUE TITLE
Duda recursos [grupos pares]

### ISSUE THREAD

**Issue by mjespinoza** [IIC2413/Syllabus-2019-2#44]
Holaa, tengo una duda con respecto a las relaciones de los recursos. Segun el enunciado de la entrega 1 se indico que cada recurso esta relacionado con un proyecto, sin embargo, en los datos entregados no hay ninguna relación de estos (por ej. los datos de recursos no tiene una columna de proyecto, ¿que se podría hacer? porque hay que hacer una consulta con respecto a esto.
Gracias de antemano! [
![duda](https://user-images.githubusercontent.com/42595117/64537191-ba3c2a80-d2f0-11e9-9956-502d74ea6b58.JPG)
](url)

**Comment by nivek0o0** [comment]
Hola @mjespinoza 

En el nombre del recurso está el nombre del proyecto.
