### ISSUE TITLE
Modelo Relacional

### ISSUE THREAD

**Issue by emena97** [IIC2413/Syllabus-2019-2#46]
Una vez que tenemos el esquema E/R normalizado, debemos entregar un pdf con esquemas de las tablas como modelo relacional? o se entiende modelo relacional como parte del proceso de crear y ocupar las nuevas tablas?

**Comment by nivek0o0** [comment]
Deben entregar ambos: el modelo E/R y el esquema relacional. Puedes ver sus diferencias aqui #35
