### ISSUE TITLE
Tutorial Servidor

### ISSUE THREAD

**Issue by emena97** [IIC2413/Syllabus-2019-2#47]
Hola! Que paso con el tutorial que decia como acceder a la base de datos?
Ahora solo esta el del servidor en la wiki

**Comment by cmp831** [comment]
Hola, desde esta [sección](https://github.com/IIC2413/Syllabus-2019-2/wiki/Tutorial-Servidor#ingresar-al-dbms-postgres) del Tutorial Servidor se explica la conexión a la base de datos.

**Comment by nivek0o0** [comment]
Todo lo que estaba en el tutorial en PDF está en la Wiki.
