### ISSUE TITLE
#VALUE!

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#48]
Aparece ese valor en algunos recursos como ongs que participan en el recurso, se asume que ninguna participa?

**Comment by nivek0o0** [comment]
Así es, al dueño de esa base de datos le falló esa referencia porque el recurso no tiene ONG's asociadas.

**Comment by absoto4** [comment]
Hola @nivek0o0 , pero si no tiene al menos una ONG asociada, cómo funciona? Se supone que cada recurso fue puesto por un grupo no acotado de ONGs. Cómo puede existir ese recurso?

**Comment by nivek0o0** [comment]
Ese recurso existe pero no está asociado a ninguna ONG. Simplemente no aparecerá en la tabla intermedia que relaciona estas dos entidades.
