### ISSUE TITLE
ONGs repetidas en el mismo recurso.

### ISSUE THREAD

**Issue by dasolari** [IIC2413/Syllabus-2019-2#50]
En el archivo recursos.csv de los datos que se subieron, hay algunos recursos en que se repite una de las ONGs que participan, por lo que no se puede crear la llave (numero, nombre). Un ejemplo de esto es el recurso de número 82881-34480-EO en la fila 31.
¿Podemos asumir que los datos están bien para simplemente filtrar esto al trabajar los datos?

**Comment by nivek0o0** [comment]
Hola, si la ONG aparece repetida para un mismo recurso, entonces deben considerarla 1 única vez. Y si aparece #VALUE!, se asume que no se conocen las ONG's para ese recurso.

La explicación es que el dueño de estos datos no tenía el conocimiento suficiente de Excel y Bases de Datos para manejar estos errores.
