### ISSUE TITLE
Entrega 2 - Consultas

### ISSUE THREAD

**Issue by nucontreras** [IIC2413/Syllabus-2019-2#51]
Para la entrega 2, ¿la página debe soportar solo las consultas propuestas en la entrega1?. De ser así, dichas consultas son muy específicas que bastaría con colocar, por ejemplo:

¿Quieres ver todas las centrales hidroléctricas?
"Consultar"

¿Eso estaría bien o hay que hacerlo de forma más general?

**Comment by arpincheira** [comment]
Hola, tu base de datos debería poder ser capaz de soportar muchas más consultas que las especificadas en el enunciado, pero en esta entrega solo se requiere que tu página tenga implementadas las consultas solicitadas y un método para poder acceder a los resultados de estas.

Ahora, dentro de lo que viene siendo la especificidad de la consulta, el ejemplo que pones es correcto, dado que quieres buscar una manera de indicar la consulta a la que el resultado correspondería. También sería correcto poner:

Consulta 1
"Respuesta"

Pero eso sería bastante básico y "_poco realista_" , ya que suponemos que las personas que ingresen a tu página no necesariamente deberían saber a lo que esta consulta corresponde, por lo que creo que no es tan recomendable implementarlo de esta manera(esto de todos modos no indica que sea incorrecto ponerlo así).

**Comment by nivek0o0** [comment]
En resumen, lo que propones es correcto sólo para las consultas que no requieren parámetros.

Lo importante es que diseñes la base de datos de la manera correcta para que soporte cualquier otra consulta, ya que podríamos pedirles más consultas en las próximas entregas. Esto quiere decir que sería incorrecto que crearas una tabla de solo termoeléctricas para que cuando te pidan la Consulta 1 hagas un `SELECT * ...`

**Comment by emena97** [comment]
Hola con respecto a esto, que pasa con la consulta 1 de los grupos pares? ya que no hay marchas para 2020... ponemos eso nomas? o implementamos una consulta para buscar por año?

**Comment by nivek0o0** [comment]
Si quieres implementar esa consulta con el año como input, adelante, nos facilitarás la corrección :)
Pero no es necesario, el mínimo exigido es la consulta específica para 2020, aunque esta retorne vacío. Pero no te preocupes por esto, ya que más adelante podríamos pedirles implementar una forma de crear marchas.
