### ISSUE TITLE
Tabla proyectos para grupos pares

### ISSUE THREAD

**Issue by FaZorrilla** [IIC2413/Syllabus-2019-2#52]
Hola,

En los grupos pares no se debe manejar a los socios, latitud, longitud, entre otros, pero los datos vienen con eso. Es necesario hacer una tabla completa con todos esos datos, aunque no los vamos a usar? o solo usamos los datos que nos piden (Tipo, Nombre)?

Saludos

**Comment by nivek0o0** [comment]
Hola @FaZorrilla  
Solo usen los que les pedimos en la Entrega 1. En este caso un grupo par no debería tener una tabla para Socios.

**Comment by FaZorrilla** [comment]
Hola, lo siento por la hora.

Me refería a la tabla en si de proyectos. En el enunciado de la entrega 1 para los grupos pares no se menciona en ninguna instancia el uso de socios, latitud, longitud, etc, por lo que no lo tenemos implementado en nuestra base de datos. Aunque no salga en el enunciado de los grupos pares, tenemos que agregar columnas de socios, latitud, etc, a nuestra tabla de proyectos?

Saludos

**Comment by nivek0o0** [comment]
No, no tienen que añadirlos. Pueden ignorar esos atributos.

**Comment by FaZorrilla** [comment]
Muchas gracias!
