### ISSUE TITLE
Consulta 5 entrega 2

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#53]
Hola. Tenía una duda sobre la consulta 5 del proyecto: se refiere a tener un socio como input y dar todos los proyectos de ese socio ordenados por numero de recursos, o a dar todos los proyectos ordenados primero por socio y luego por numero de recursos?

**Comment by nivek0o0** [comment]
La consulta 5 de los grupos impares se refiere a todos los proyectos de cada uno de los socios, por lo tanto no existe _input_.

Ahora bien, ustedes deberían encontrar una manera amigable de mostrar los resultados (para evitar mostrar 200.000 filas de la tabla de una pura vez). Por ejemplo:

- Listar cada uno de los socios con un hipervínculo, y al hacer click nos lleva a una página donde se muestran sus proyectos listados por # de recursos.
- Mostrar socios y proyectos ordenados en la misma página, pero entregando los resultados de forma parcializada, con un botón de `mostrar más` al final.
