### ISSUE TITLE
Dependencias funcionales en diagramas E/R

### ISSUE THREAD

**Issue by kylevon** [IIC2413/Syllabus-2019-2#54]
Para escribir una dependencia funcional entre dos variables, ¿se debe mostrar de esta forma? 
<img width="361" alt="ER" src="https://user-images.githubusercontent.com/46159219/64712437-9532ed80-d491-11e9-9d85-8f64e1b979b9.png">
Que diría que con el atributo 2 se puede conseguir el atributo 1. Luego en una tabla serían dos columnas 

|atributo 2 (key)| atributo 1|
|---------------|-----------|

**Comment by nivek0o0** [comment]
Hola @kylevon 
Para escribir una dependencia funcional no es necesario hacer un diagrama, basta con escribir:
`atributo2 -> atributo1, atributo3, etc...`

**Comment by kylevon** [comment]
Perfecto, entonces en el diagrama, si tenemos la dependencia funcional anterior, ¿ponemos los atributos en el diagrama de entidad relación sin la flecha entre ellos? Y al mismo tiempo ¿en las tablas mostramos esta dependencia funcional?

**Comment by nivek0o0** [comment]
Es mejor que las dependencias funcionales se muestren aparte del modelo E/R y del esquema relacional. Así queda todo más pulcro.
