### ISSUE TITLE
Llaves socios y proyectos

### ISSUE THREAD

**Issue by JaviFerrada** [IIC2413/Syllabus-2019-2#55]
Hola! revisé las bases de datos y me di cuenta que ningún nombre de socio o proyecto se repite, puedo usar estos como llaves? o les debo asignar un id, ya que posteriormente si se podría dar esta situación?

**Comment by juanreutter** [comment]
Puedes usarlos si asumes que esos atributos son llaves, semánticamente siempre es mejor usar los campos que son llaves: así si ingresan a otro socio con el mismo nombre, te va a dar error.  

Ahora, en general, en la práctica uno no usa strings como llaves simplemente por que para la parte interna son un cacho (en el computador son representados como números mucho más grandes que los ids).
