### ISSUE TITLE
Tiempo consulta

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#56]
Hola, queremos probar las consultas que tenemos diseñadas para ver si están bien, nose si son nuestro computadores o el servidor, pero al final no tira ningun resultado ya que tira error. Probamos tanto desde putty como de la pagina web.  Que podemos hacer para probar las consultas?

**Comment by cmp831** [comment]
Hola, qué tipo de comandos tienen? Consultas SQL o código PHP? Si ya tienen montado la base de datos en el servidor con los datos importados, pueden ejecutar las consultas SQL usando psql en el servidor. Si ya tienen el código PHP hecho, basta con subir los archivos PHP al servidor, y probar la página ingresando directamente desde el navegador. 

Puedes especificar un poco más el error que están encontrando? En teoría no deberían tener que probar cosas en local, se otorga el servidor para que no tengan que setear un entorno en sus propios computadores.
