### ISSUE TITLE
foreing keys en diagrama ER

### ISSUE THREAD

**Issue by jirarrazabal** [IIC2413/Syllabus-2019-2#57]
Hola! en el diagrama ER si una entidad utiliza un foreing key, ¿Es necesario escribirla como atributo, o basta solo que esté en la entidad de la cual se "heredo"? Mucahs Gracias!

**Comment by nivek0o0** [comment]
Sí, también se escriben las FK como atributos en la entidad que hereda.

**Comment by crvargasu** [comment]
Tengo una duda, en las clases cuando hablan del tema lo colocan de la siguiente manera

![imagen1](https://user-images.githubusercontent.com/48322767/64742575-1494e100-d4d3-11e9-84f9-0c7d2373e174.PNG)

Entonces habia entendido que no habia que escribir las FK como atributos de la entidad que hereda

**Comment by nivek0o0** [comment]
Creo que @jirarrazabal se refería a las FK en general y mi respuesta fue que también se escriben en la entidad de destino. 

Respecto a la especialización que ilustras, tienes razón, los atributos comunes no se "heredan" (repiten). Pero si hay que heredar la primary key de la entidad Padre. De lo contrario no sabríamos cual es el atributo para hacer los JOINs.

Hay muchos diagramas como los que vieron en clases cuyo objetivo es enseñar que la especialización permite incorporar atributos específicos para un subconjunto de las entidades y así evitar Nulos. Pero esos diagramas distan un poco de la implementación real.

Algo un poco más realista sería:
![especializacion2](https://user-images.githubusercontent.com/20782451/64743290-ab629d00-d4d5-11e9-8629-4e42e371f23d.png)
