### ISSUE TITLE
Consulta SQL

### ISSUE THREAD

**Issue by valeeeriquelme** [IIC2413/Syllabus-2019-2#58]
Quería saber si existía alguna forma de luego haber creado una tabla, ver cuál columna es su PRIMARY KEY.

**Comment by nivek0o0** [comment]
`\d+ <tablename>` te entrega sus atributos y restricciones

**Comment by arpincheira** [comment]
Hola, aprovecho de comentar que si quieres buscar más información sobre este u otro tipo de comandos que podrían serte de utilidad a lo largo del proyecto, te recomiendo revisar la documentación de postgress a la que puedes acceder usando este [link](https://www.postgresql.org/docs/10/sql-commands.html)
