### ISSUE TITLE
Preprocesamiento de datos

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2413/Syllabus-2019-2#59]
Hola! Tengo dudas sobre los detalles del preprocesamiento de datos, por ejemplo, ¿Hay que subir el script que utilicemos? ¿Podemos usar cualquier libreria? Actualmente lo estoy haciendo en python y estoy usando la libreria csv, y unidecode.

Saludos!

**Comment by nivek0o0** [comment]
Hola
No hay ninguna restricción para el pre-procesamiento de los datos. Pueden usar las librerías que quieran.

Lo único importante es que no se pierdan datos, porque eso afectaría el resultado de las consultas y por lo tanto la evaluación de la entrega.

**Comment by BenjaPrograma** [comment]
Entonces se puede modificar "a mano" en excel también? Y después tendriamos que subir estos archivos a mano a la página?

**Comment by nivek0o0** [comment]
Claro ;)
