### ISSUE TITLE
Proyecto: Minas con más de un mineral

### ISSUE THREAD

**Issue by cristobalwelch** [IIC2413/Syllabus-2019-2#61]
Hola!

Revisando los proyectos, me di cuenta que hay algunas minas en las que se extrae más de un mineral. En el enunciado dice que debemos asumir que solamente habrá un mineral por mina.

En estos casos, ¿qué es lo que debemos hacer? ¿Usar un criterio definido por nosotros para elegir uno de los minerales? ¿No considerar esos proyectos?

Gracias!

**Comment by arpincheira** [comment]
Hola, esta consulta es similar a la de la issue #50, por lo que te recomiendo echar un ojo a la respuesta

**Comment by cristobalwelch** [comment]
Ok, gracias!
