### ISSUE TITLE
Duda suma de fechas

### ISSUE THREAD

**Issue by jalliende** [IIC2413/Syllabus-2019-2#62]
Como se puede hacer para sumar dias a una fecha, ya que trate haciéndolo con "+" pero me tira error y desde el jupyter si me deja pero solo me suma los dias totales, es decir lo dias que llevaba del mes mas los dias que le sume.

**Comment by arpincheira** [comment]
Hola, recomiendo que busques esa información en este link https://www.postgresql.org/docs/8.1/functions-datetime.html y que pongas énfasis a lo que es la documentación de la función date_part, eso podría serte de utilidad.
