### ISSUE TITLE
[Entrega 2 - Impares]  Consulta 3

### ISSUE THREAD

**Issue by AndresFaure** [IIC2413/Syllabus-2019-2#63]
Hola. La consulta 3 para los impares dice lo siguiente;

> Muestre todos los recursos asociados a minas, abiertos entre una fecha a y una fecha
> b. 

Cuando se dice que se busca al recurso abierto entre la fecha _a_ y _b_, se espera que incluyamos a estas fechas dentro del rango de búsqueda? (En el fondo pregunto si tenemos que usar '<=' y '>=' o '<' y '>').

**Comment by nivek0o0** [comment]
Hola, el rango de fechas es inclusivo con los bordes!

**Comment by AndresFaure** [comment]
Dale! Gracias
