### ISSUE TITLE
Datos en inglés

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#64]
Hola, en la Issue #40 se habla de que postgres admite infinidad de codificaciones, incluyendo las ñ's y ç's que supongo no existen en el inglés, entonces ¿el único carácter con problemas es el acento? ¿Es lo único que se nos pide arreglar de los campos de texto? ¿Qué pasa con los apostrofes o con los puntos y comas de los nombres de los proyectos, hay que sacarlos o dejarlos?

**Comment by nivek0o0** [comment]
Claro

**Comment by quememo** [comment]
> Hola, los tildes tampoco representan un problema para la base de datos, ya que pueden ser almacenados y consultados correctamente.
> 
> Los apostrofes y puntuación presentes en algún atributo deben mantenerse, pues son parte de él. Para que ellos no representen un problema en la separación de los valores del CSV, esos strings fueron encerrados entre "comillas dobles".
> 
> Lo que ustedes deben arreglar es la estructura de los datos, no el contenido.

Como mencionas que solo hay que arreglar la estructuras de los datos y no el contenido, me parece haber encontrado un error en el contenido de los .csv , donde en _recursos.csv_ aparece la región de tramitación **XI de Aysén del General Carlos Ibáñez del Campo** con tilde en Ibáñez pero en _proyectos.csv_ aparece la región **XI de Aysén del General Carlos Ibañez del Campo** sin tilde en Ibañez. Esto provoca que al hacer alguna consulta respecto a las regiones (como la 5 de la Entrega 1) aparezcan 2 valores para esta misma región.

**Comment by quememo** [comment]
> > Hola, los tildes tampoco representan un problema para la base de datos, ya que pueden ser almacenados y consultados correctamente.
> > Los apostrofes y puntuación presentes en algún atributo deben mantenerse, pues son parte de él. Para que ellos no representen un problema en la separación de los valores del CSV, esos strings fueron encerrados entre "comillas dobles".
> > Lo que ustedes deben arreglar es la estructura de los datos, no el contenido.
> 
> Como mencionas que solo hay que arreglar la estructuras de los datos y no el contenido, me parece haber encontrado un error en el contenido de los .csv , donde en _recursos.csv_ aparece la región de tramitación **XI de Aysén del General Carlos Ibáñez del Campo** con tilde en Ibáñez pero en _proyectos.csv_ aparece la región **XI de Aysén del General Carlos Ibañez del Campo** sin tilde en Ibañez. Esto provoca que al hacer alguna consulta respecto a las regiones (como la 5 de la Entrega 1) aparezcan 2 valores para esta misma región.

Esto también ocurre con la región **XII de Magallanes y de La Antártica Chilena** (en un .csv aparece con tilde y en el otro no)

**Comment by nivek0o0** [comment]
Hola @quememo 
No deberías tener esa redundancia en tu base de datos, osea no deberías almacenar Comuna y Región en diversas tablas. Si lo haces así tu modelo no estaría normalizado. Deberías tener esos strings una única vez en tu BD. Ver #84 

Imagina el día de mañana una región cambia de nombre. Es mucho más fácil modificarla en una sola tabla que en N tablas. O imagina si queremos añadir la población de la comuna porque necesitamos priorizar los recursos, es válido el mismo argumento anterior.

**Comment by quememo** [comment]
No me has entendido, en mi base de datos lo tengo normalizado y efectivamente es fácil modificarla si es que cambia de nombre, sin embargo dada esa diferencia en el tilde presente en los archivos .csv entregados se consideran regiones diferentes y causa un problema

**Comment by nivek0o0** [comment]
Ahh, esa sería una excepción en la que hay que modificar el contenido de los datos para que quede todo consistente.

Por otra parte, creo que el problema se te origina porque dejaste en Proyecto y en Recurso el nombre de la comuna y no pusiste la restricción de lláve foránea. Una forma sencilla de solucionarlo era ocupar un ID para identificar las comunas, pero a esta altura lo más rápido sería actualizar las filas con Postgres para poner los tíldes.

**Comment by quememo** [comment]
Pero como bien tu mencionabas, no correspondía a nuestro trabajo arreglar esos detalles de contenido (específicamente en la falta de consistencia entre los .csv con los tildes presente en las regiones) sino que la estructura de los datos, cierto?

**Comment by nivek0o0** [comment]
Cuando mencioné que _debían arreglar la estructura y no el contenido_ no sabía que existía esa inconsistencia en el nombre de las regiones. Si ustedes llegan a encontrar un detalle así, en que dos celdas son casi exactamente iguales y difieren tan solo en 1 tilde, está claro que deben arreglarlo.  

Su trabajo también incluye ser **proactivos** y solucionar los "problemas" que van encontrando en el camino. (Tu planteaste que se trata de un **problema**, entonces había que hacer algo al respecto, ¿o no?)
