### ISSUE TITLE
Duda Socios

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#67]
Una duda, si tengo esto:

sid | nombre | apellido | nacionalidad
-- | -- | -- | --
1 | Anna | Monika Fatih | Griega
2 | Anna Monika | Fatih | Griega

¿Son dos socios distintos o para el proyecto debería tomarlos como el mismo?

**Comment by nivek0o0** [comment]
No te compliques y déjalos como socios distintos. La decisión no tendrá influencia alguna porque esa persona no participa de ningún proyecto.
