### ISSUE TITLE
Duda IsA

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#68]
![image](https://user-images.githubusercontent.com/37162670/64838892-a8e26f00-d5cb-11e9-8bea-a017b7a6c84e.png)

En este ejemplo se puede ver que se tiene el producto educativo y computacional, pero no hay algo como una atributo "tipo" que diga explicitamente "educacional" o "computacional", entiendo que no sería correcto ponerla ya que en la tabla de ProductoEducacional seria super redundante la columna "tipo" que dijera siempre lo mismo. ¿estoy en lo correcto? ¿o debería poner una columna que diga explicitamente Central, minera o vertedero?

**Comment by nivek0o0** [comment]
La columna **tipo** debería ir en la entidad Madre. Ahí tendría sentido para poder filtrar solo las Minas (por ejemplo). Luego uno podría hacer el JOIN con las entidades Hijas para recuperar los atributos específicos.
