### ISSUE TITLE
Carpeta entrega 2

### ISSUE THREAD

**Issue by MGilB** [IIC2413/Syllabus-2019-2#69]
Hola, tengo una duda con la forma de entregar los archivos. Suponiendo que el código de mi pagina está en la carpeta "app" ¿tengo que dejar esa carpeta en la carpeta Sites o tengo que dejar todos los archivos?
 Mi duda está en que si dejo la carpeta entera para entrar a la página la url sería así: 
.../Sites/**app**/index.php en vez de .../Sites/index.php

**Comment by nivek0o0** [comment]
Hola, reconozco que el enunciado quedó un poco ambiguo en ese punto. 

La ruta correcta de tu página principal es:
`.../Sites/Entrega2/index.php`

**Comment by ninifdr** [comment]
Hola no entiendo bien cómo sería.
Si los archivos de la página están dentro de sites, por qué la ruta incluye "Entrega2" ?

**Comment by nivek0o0** [comment]
Lo pensé mejor y lo más fácil para ustedes es que el proyecto completo esté directamente dentro de **Sites**. Yo me encargaré de separar las próximas entregas dado que son acumulativas en cuanto a funcionalidades.

**Comment by nivek0o0** [comment]
Lo pensé mejor y lo más fácil para ustedes es que el proyecto esté directamente dentro de **Sites**.

Yo me encargaré de separar las entregas que son acumulativas en funcionalidades. Además así respetamos lo que dice el Enunciado.

Por lo tanto, la ruta correcta finalmente será

`...Sites/index.php`
