### ISSUE TITLE
Comparación de fechas

### ISSUE THREAD

**Issue by absoto4** [IIC2413/Syllabus-2019-2#7]
Si tengo un atributo de tipo date, ¿se puede comparar con otro tipo date? Por ejemplo:
2000-10-02 < 2008-12-03

**Comment by viantirreau** [comment]
Sí!
En SQLite solo tienes que rodearlo con comillas simples y lo interpreta como fecha.
Encontré esto en la actividad de hoy:
```sql
SELECT producto, SUM(precio*cantidad) AS ventaTotal
FROM compra 
WHERE fecha > '2018-01-10'
GROUP BY producto;
```

Saludos!

**Comment by absoto4** [comment]
Y si lo hacemos con álgebra relacional igual cuenta?

**Comment by arpincheira** [comment]
Hola, efectivamente tal como escribe @viantirreau esa sería la solución a tu consulta dentro de lo que corresponde a SQLite. Ahora, con respecto a lo del álgebra relacional, es correcto utilizar el mismo principio, es decir, está permitido poner date1 > date2 o year(fecha) < 2019 y cosas por el estilo.

Espero haberte ayudado.

**Comment by absoto4** [comment]
Ahhh, ya. Muchas gracias!
