### ISSUE TITLE
Consultas en Pagina WEB

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2413/Syllabus-2019-2#70]
No me quedo claro como es que tengo que presentar la información en la página web, coloco un cuadro de input que reciba la consulta en SQL y que luego la ejecute la pagina? O debo hace inputs en donde la informacion puede variar, por ejemplo:
`SELECT name FROM familia WHERE edad>23;`
En este caso, la información que puede variar es el '23', porque puedo querer elegir otra edad.
O solo coloco las consultas ya realizadas en la página?

**Comment by cmp831** [comment]
Hola, debes hacer inputs para recibir solo información que debe variar. Nunca debes recibir la consulta de sql como texto y ejecutarlos directamente en la base de datos, imaginate si alguien enviara `drop table familia`. Perderás toda los datos guardado en esa tabla, más adelante van a ver cómo evitar inyecciones de SQL en clases con más detalles.

**Comment by lfuenzalida2** [comment]
Muchas Graciaas
