### ISSUE TITLE
Librerías javascript página web

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#72]
Hola, buenas tardes.

Estuve investigando cómo hacer para no poner una tabla de 10000000 filas de una en la página web, y encontré una solución simple con jQuery. Se puede usar este módulo, específicamente algo de este estilo?
```javascript
$(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
});
```

**Comment by nivek0o0** [comment]
Sí puedes usarlo! Nosotros estaremos felices de que aprendan javascript básico.
