### ISSUE TITLE
killed postgresql

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#73]
Hola
pertenezco a grupo impar y estoy probando algunas consultas que necesito desde el servidor, me pasa que se demora bastante y luego muere mi consulta, será porque mi internet es lento ? o mis tablas tienen demasiado datos, principalmente este problema lo tengo con la tabla que relaciona los id de los recursos con los id de los proyectos.
Saludos. 
![Captura de pantalla de 2019-09-13 21-35-39](https://user-images.githubusercontent.com/42189869/64901389-f237ca80-d66e-11e9-916e-62d7ed9b9ad2.png)

**Comment by cmp831** [comment]
Hola, creo que te falta un inner join entre la tabla de `recurso_asociado` y `fecha_dictamen`. Sin definir que se está haciendo un join, la base de datos lo trata como un outer join, cual genera una cantidad muy grande de filas. No ayuda que además de hacer un outer join estás haciendo una consulta anidada. Al realizar la consulta, Postgres llena la memoria del servidor por la cantidad de filas que genera la consulta, y el kernel tiene que matar al proceso de Postgres como auto defensa.
