### ISSUE TITLE
Carácters en Inglés 

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#74]
Hola, tengo una duda con  estos carácteres, como los tildes, o ñ's, no entiendo bien si debo preprocesarlos antes de trabajar con postgres o solo debo hacer que al usar postges, éste debe admitir dicha codificación.

**Comment by nivek0o0** [comment]
Hola, te pido porfavor leer las issues (abiertas y cerradas) antes de preguntar. De esa forma evitamos tener preguntas duplicadas.
