### ISSUE TITLE
Modelo ER circular

### ISSUE THREAD

**Issue by Kitaps** [IIC2413/Syllabus-2019-2#75]
Hola, 

somos un grupo par y al hacer nuestra modelación E/R nos queda un circulo, esto significa que hay redundancia? 

A lo que me refiero con circulo es que 
Movilisación tiene id_ong é id_projecto
Recursos tambien tiene id_ong é id_projecto

Está mal eso?

De antemano muchas gracias

**Comment by nivek0o0** [comment]
Hola, la situación que planteas no está mal y no significa que haya redundancia.

Ahora, en el caso hipotético de que las movilizaciones y los recursos estuviesen relacionados, modelar cada relación como binaria en vez de una gran relación cuaternaria probablemente sea redundante.

**Comment by Kitaps** [comment]
Gracias, ahora andamos más tranquilos :)
