### ISSUE TITLE
Duda Relacion sin key 2

### ISSUE THREAD

**Issue by ciquezada** [IIC2413/Syllabus-2019-2#76]
continuando la duda de la issue #26 :

ONG | Recurso
1 | 1
1 | 2
2 | 1

si hago que ambas llaves sean primarias, ¿no hará esto que la ONG con id 1 solo pueda aparecer una vez, lo que impediría que una ONG participe en mas de un recurso?

además, no entiendo bien como manejar las llaves foráneas en estos casos con tablas de relaciones, si por ejemplo el recurso dependiera de la ONG, ¿habría que hacer que el recurso tuviese por llave foránea su id en la tabla de relaciones?

**Comment by nivek0o0** [comment]
> si hago que ambas llaves sean primarias, ¿no hará esto que la ONG con id 1 solo pueda aparecer una vez, lo que impediría que una ONG participe en mas de un recurso?

La llave primaria funciona como un conjunto: todos los atributos de la llave primaria deben ser iguales para que no se te permita insertar la fila. Se estaría evitando lo siguiente:
ONG | Recurso
1 | 2
1 | 2 <- esta no se podría


Respecto a las llaves foráneas, simplemente la tabla intermedia recoge los IDs (o llave primaria) de ambas entidades que se están relacionando. Estos dos atributos, además de ser PK aquí, son FK.
No entiendo tu ejemplo de que el recurso dependiera de la ONG, si eso pasara probablemente no tengas una relación N:M

**Comment by ciquezada** [comment]
y como se hace una relacion 1:1, lo que hice fue hacer que una id fuese primaria y la otra la puse como unique, esta bien?
