### ISSUE TITLE
Error al conectar a la base de datos en PHP

### ISSUE THREAD

**Issue by mjvarela** [IIC2413/Syllabus-2019-2#78]
Cuando intento conectarme a las base de datos siguiendo el ejemplo de la ayudantía con la instancia PDO me tira el siguiente error 
![Captura de Pantalla 2019-09-15 a la(s) 18 08 15](https://user-images.githubusercontent.com/42159497/64927653-e3beef80-d7e3-11e9-9f08-a0151628183d.png)

He buscado mucho en internet y no he logrado arreglarlo.

**Comment by nivek0o0** [comment]
Hola, el error ya fue solucionado. 
De todas maneras estamos trabajando para que no vuelva a ocurrir!
