### ISSUE TITLE
No me carga consulta en la pagina

### ISSUE THREAD

**Issue by crvargasu** [IIC2413/Syllabus-2019-2#79]
Hola
Estaba realizando la consulta 6 de los grupos pares y al colocar el comando no me carga la página, lo cual es muy raro porque al utilizar el mismo comando en el cmd me funciona correctamente

La página me deja de cargar cuando intento hacer un join, el comando es el siguiente:

"SELECT *
   FROM recursos_tramite, rrss
   WHERE rrss.proyecto = recursos_tramite.nombre_proyecto;";

**Comment by nivek0o0** [comment]
Hola, el problema es que están haciendo **fetchAll()** a las 444.177 filas que tiene el resultado de la consulta. Modifiqué su archivo PHP poniendo un límite a la consulta y ahora si carga la página. Esta no es la solución definitiva, así que deben pensar una forma de solucionar esto. (Miren otras issues donde se habla de cómo mostrar muchas filas)

Pueden usar `SELECT COUNT(*) ...` para saber cuantas filas tiene una consulta.
