### ISSUE TITLE
Recursos

### ISSUE THREAD

**Issue by acpopper** [IIC2413/Syllabus-2019-2#8]
Hola!
Podrían dar un(os) ejemplo(s) de lo que sería un recurso?
Y en el enunciado dice "Interesa almacenar la fecha en que se realizó el recurso[...]" y luego si se aprobó o rechazó además poner la fecha en la que se dictaminó ese estatus.
Luego para la consulta 3 dice "Muestre todos los recursos asociados a minas, abiertos entre una fecha a y una fecha b". En este caso "abiertos" hace referencia a cual fecha? Y a qué se refiere con "fecha en que se realizó el recurso"?
Gracias

**Comment by nivek0o0** [comment]
Hola @acpopper 

_Realizar un recurso_ equivale a crearlo/presentarlo/abrirlo, que ocurre cuando una ONG lo va a presentar ante algún organismo de autoridad. El recurso queda inicialmente en estado **abierto**.

Cuando este organismo resuelve el recurso, este queda **cerrado**, pero además adquiere un estado de **aprobado** o **rechazado**. 

La idea es que captures ambos instantes, cuando se crea y cuando se resuelve, además de la resolución final. Queda a tu criterio cómo modelar esta situación.

Respecto a la consulta 3, se piden los recursos que fueron creados entre **a** y **b**

**Comment by Kitaps** [comment]
> Respecto a la consulta 3, se piden los recursos que fueron creados entre a y b

Podrían agregar eso en el enunciado, que está la posibilidad de confundirse y pensar que se refiere a los recursos que se encuentran en estado abierto entre esas fechas. Igual con tu respuesta ya me quedó claro, gracias.

**Comment by Seld0nn** [comment]
Los recursos tienen nombre? o basta con un retornar un identificador en la consulta 3?

**Comment by clolate** [comment]
Un recurso abierto entonces se puede considerar en tramite? o esta inicialemte en estatus None?

**Comment by juanreutter** [comment]
Los recursos tienen nombre en la medida que ustedes quieran, eso no está específicado. Lo mismo con el tipo de dato.
