### ISSUE TITLE
Error psql/servidor

### ISSUE THREAD

**Issue by VicenteMerino** [IIC2413/Syllabus-2019-2#80]
Hola, me sale el siguiente error al tratar de ingresar a psql, no se que será. Espero me puedan ayudar pronto.
![image](https://user-images.githubusercontent.com/47841749/64928066-567e9980-d7e9-11e9-8610-b0b7c0d08ce3.png)

**Comment by ciquezada** [comment]
Grupo85 con el mismo problema
![image](https://user-images.githubusercontent.com/37162670/64928090-ad846e80-d7e9-11e9-978d-dc64d38e105b.png)

**Comment by tatanpoker09** [comment]
Grupo 60 con el mismo problema, se cayó la base de datos del servidor

**Comment by cristianoberpaur** [comment]
Grupo 8 con el mismo error

**Comment by BernaValdivieso** [comment]
Grupo 41 igual

**Comment by nrrosenberg** [comment]
grupo 10 tambien

**Comment by castrillini** [comment]
grupo 74 también :(

**Comment by niguzman** [comment]
grupo 19 igual :C

**Comment by nivek0o0** [comment]
Hola, el error ya fue solucionado. 
De todas maneras estamos trabajando para que no vuelva a ocurrir!
