### ISSUE TITLE
Error con el servidor

### ISSUE THREAD

**Issue by ninifdr** [IIC2413/Syllabus-2019-2#81]
Hola! Mi página estaba funcionando perfecto y ahora me aparece este error cuando hago una consulta
![Captura de Pantalla 2019-09-15 a la(s) 18 48 38](https://user-images.githubusercontent.com/42162406/64928083-8f1e7300-d7e9-11e9-9764-fb1a75f8d7a6.png)

**Comment by valeeeriquelme** [comment]
Mismo problema aquí

**Comment by JoseAvanzada2019** [comment]
mismo aquí

**Comment by flolju** [comment]
A mi tambien

**Comment by nivek0o0** [comment]
Hola, el error ya fue solucionado. 
De todas maneras estamos trabajando para que no vuelva a ocurrir!
