### ISSUE TITLE
Comando SQL

### ISSUE THREAD

**Issue by niguzman** [IIC2413/Syllabus-2019-2#83]
Hola,
Existe algún comando para poder ver que tipo de dato tienen las tablas? no recuerdo exactamente qué número le puse a los varchar() al momento de crear las tablas y me lo piden 
![image](https://user-images.githubusercontent.com/48304981/64932230-e2a5b680-d813-11e9-9950-8f6b14e80e3d.png)

**Comment by cmp831** [comment]
Hola, dentro de `psql` puedes ejecutar `\d+ nombreTabla` para obtener los datos de las columnas. Otra herramienta que puedes usar el el comando `pg_dump` que se ejecuta direnctamente en la consola. Un ejemplo de cómo usarlo lo puedes encontrar [acá](https://stackoverflow.com/a/2594564). Recuerda revisar la [documentación](https://www.postgresql.org/docs/current/app-pgdump.html) si tienes alguna duda sobre el comando.
