### ISSUE TITLE
tabla región-comuna

### ISSUE THREAD

**Issue by teverde** [IIC2413/Syllabus-2019-2#84]
En clases se dió como ejemplo que se podía sacar la columna región de las entidades proyecto y recurso a una tercera, dejando como llave la columna comuna.
Mi pregunta es si esta tabla sería relación o entidad y como se conectaría a las dos entidades que mencioné, porque no me termina de hacer sentido en el diagrama

**Comment by nivek0o0** [comment]
Hola, esa nueva tabla de Comuna&Región sería una entidad, porque su existencia no depende de nada más, es independiente.

Y dado que se relaciona 1:N tanto con Proyectos como Recursos, no es necesaria una tabla intermedia para dichas relaciones. Basta que su llave primaria viaje a esas otras entidades para ser llave foránea.
