### ISSUE TITLE
Join entre tablas

### ISSUE THREAD

**Issue by patogramador** [IIC2413/Syllabus-2019-2#85]
![tabla](https://user-images.githubusercontent.com/48293109/64965274-12d07200-d873-11e9-870f-b4e6036e4086.PNG)
Al hacer join entre dos tablas se me estan uniendo de esta forma en vez de unirse solo las filas con el mismo id, nose si debiese ser así o estoy haciendo algo mal.

**Comment by nivek0o0** [comment]
Hola, podrías colocar la consulta SQL para ver si el problema está allí?

**Comment by patogramador** [comment]
SELECT * FROM proyectos, centrales

**Comment by nivek0o0** [comment]
Con esa consulta estás haciendo un Producto Cruz, no un JOIN. Para hacer un JOIN tienes las siguientes opciones:

- SELECT * FROM Tabla1, Tabla2 WHERE Tabla1.atri1 = Tabla2.atri2;

- SELECT * FROM Tabla1 JOIN Tabla2 ON Tabla1.atri1 = Tabla2.atri2;

También existen otros tipos de JOINs más elaborados, como un LEFT OUTER JOIN que conserva las filas de la tabla de la izquierd si no hubo coincidencias. Te sugiero investigarlos.
