### ISSUE TITLE
Problema fecha consulta 3 (impares)

### ISSUE THREAD

**Issue by Tngarrido** [IIC2413/Syllabus-2019-2#88]
Hola
he probado mi consulta ingresando los datos en el servidor y funciona perfecto, pero estoy teniendo problema con la variable que guarda las fechas input ingresadas por el usuario. Si ingreso los datos directamente, me funciona 
![image](https://user-images.githubusercontent.com/42189869/64984806-f1cf4780-d899-11e9-8f0d-810f11470a9c.png)
Pero al ingresar los datos como variable, mi consulta no consigue ningun dato (vacio), he incluso 
si guardo el valor directo en la variables. 
![image](https://user-images.githubusercontent.com/42189869/64984921-2ba04e00-d89a-11e9-9573-9ba30ada3afb.png)
como no consigo datos, imprimo los valores de mis variables y realmente son esos los valores, no entiendo que pasa.
![image](https://user-images.githubusercontent.com/42189869/64985203-bda85680-d89a-11e9-9e63-385799dad9c6.png)

Saludos

**Comment by Nitsuga69** [comment]
Hola!!
Tuvimos el mismo problema. Pudimos solucionarlo pidiendo que las fechas del input sean escritas entre comillas. No sé porque funciona solo con las comillas pero para que pruebes.

**Comment by arpincheira** [comment]
Hola, efectivamente como dice @Nitsuga69 su problema es debido a que el valor que les entrega la variable está sin comillas simples, lo que produce que postgress no sea capaz de procesar su consulta, una recomendación es que dentro de la consulta pongan la variable misma entre comillas, es decir: '$fecha' envés de $fecha que es como lo tienen actualmente(recuerden que deben utilizar comillas simples al hacerlo, dado que su consulta misma ya posee comillas dobles al momento de definirla)
