### ISSUE TITLE
[Entrega 1 Par] proyecto P 

### ISSUE THREAD

**Issue by Kitaps** [IIC2413/Syllabus-2019-2#9]
En las consultas, la consulta nr. 3 dice: 

> 3. Muestre todas las ONG que participan en un recurso para algún proyecto P.

El proyecto P sería para un nombre P o una id P ? 

Gracias

**Comment by nivek0o0** [comment]
Hola @Kitaps 

En general las entidades se buscan por nombre, porque el usuario final no entiende de ID's (ni debería). Las buenas prácticas consisten en utilizar textsearch, regex o el operador LIKE, pero nosotros no les pediremos eso, así que pueden asumir que **P** es el nombre exacto.

**Comment by clolate** [comment]
Ese "un recurso" se deberia interpretar como: "un recurso R para algún proyecto P", o ese uno es que tiene solo 1 recurso, o que tiene al menos 1 recurso?

**Comment by clolate** [comment]
Ademas que es un recurso vigente? significa que esta en tramite? 

abierto == tramite == vigente?

**Comment by juanreutter** [comment]
Sobre lo del recurso: En este tipo de casos yo prefiero que dejen su interpretación como supuesto, por que realmente es un detalle (nada cambia de la modelación por que se trata de soportar consultas). Pero cuando lo escribimos pensamos en al menos un recurso. 

Sobre lo de vigente: lo mismo. Nosotros lo pensamos como abierto == tramite == vigente.
