### ISSUE TITLE
Problema cargar tablas

### ISSUE THREAD

**Issue by niguzman** [IIC2413/Syllabus-2019-2#90]
Hola,
había estado cargando las tablas sin problemas pero de la nada dejó de funcionarme y no logro encontrar donde está el error :C 
![image](https://user-images.githubusercontent.com/48304981/65008572-31208700-d8e0-11e9-84db-a48ecceb2b2a.png)

Ya revisé con Filezilla y el archivo efectivamente está arriba

**Comment by mimunoz11** [comment]
Hola, lo lograste solucionar?

**Comment by cmp831** [comment]
Hola, asegurense que el csv que quieren cargar exista en la ruta que estan especificando. Sobre la ruta, pueden ver la issue #31

**Comment by niguzman** [comment]
No he podido solucionarlo, ya revisé y sí, esa es la ruta

**Comment by mimunoz11** [comment]
\COPY Lugar from 'Sites/Entrega2/lugar.csv' DELIMITER ',' CSV HEADER

al fin con ese codigo me funcionó
prueba agregando Sites, ve las mayúsculas, en el intento 1001 me salió, por último, intenta sacando el ";" que tienes al final

**Comment by niguzman** [comment]
No me funciona porque no tengo Entrega2 en sites :/

**Comment by nivek0o0** [comment]
No importa dónde tengas los CSV. 
Lo importante es que puedes usar rutas que son relativas al lugar donde ejecutaste **psql**
