### ISSUE TITLE
Input consultas

### ISSUE THREAD

**Issue by Kitaps** [IIC2413/Syllabus-2019-2#92]
Hola, 

En el enunciado dice que para hacer las consultas tenemos que hacer las consultas de SQL de la entrega 1. 

Por ejemplo: 
> 1. Muestre todas las marchas planicadas para el 2020.

Mi duda es que entonces en la pagina web tenemos que hacer un cuadro de input donde alguien meta el año y entonces se despliegue el resultado. Y ahí entonces se meta 2020?

O simplemente tenemos que mostrar la consulta ya realizada en la pagina, sin input?

De antemano muchas gracias

**Comment by arpincheira** [comment]
Hola, 
Resulta ser que en el enunciado están escritos los requisitos mínimos para esta entrega, en otras palabras, poder responder solo la consulta solicitada, por lo que queda a su criterio ver como hacen para poder cumplir con esto, es decir, está bien que den el espacio para que se puedan hacer consultas más allá de lo solicitado, pero no es estrictamente necesario, por lo que se pueden conformar con la segunda opción que describiste.

**Comment by Kitaps** [comment]
gracas :)
