### ISSUE TITLE
Duda parte 2.1: Intersección

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2413/Syllabus-2019-2#94]
Mi primera duda es que para recorrer los elementos en la lista se permite utilizar los índices de esta (i.e lista[index]) o es necesario crear una especie de lista ligada? y mi segunda duda es si es **estrictamente** necesario recorrer  todos los elementos de la lista, es decir, se pueden dejar elementos sin recorrer?

**Comment by arbiocanpion** [comment]
Hola!
La idea de recorrer la lista, es usar la clase NodoBtree como lista ligada, ya que de esta manera pueden replicar la estructura del B+tree que es el objetivo de la actividad.
En segundo lugar, es estrictamente necesario recorrer todos los elementos de la lista que contenga a los usuarios. Aunque, si implementas de manera correcta el algoritmo deberías recorrer completamente las dos listas.

**Comment by clolate** [comment]
Entonces, en la parte2, hay que crear el árbol, poblarlo y después hacer la intersección?

**Comment by arbiocanpion** [comment]
Exactamente, pero ademas, hay que realizar el join entre usuarios y favoritos, pero recorriendo solo una vez ambas listas

**Comment by mimunoz11** [comment]
¿esta prohibido entonces usar indices?

**Comment by arbiocanpion** [comment]
@mimunoz11, explica un poco mas tu idea para poder tener una idea mas clara de lo que quieres hacer.

**Comment by mimunoz11** [comment]
Recorrí ambas listas, solo una vez, pero sin usar Btree, en el fondo en vez de hacer .siguiente hice contador += 1, no se si se entiende, pero verifique y cumple lo pedido solo que recién me di cuenta que había que usar Btree :((

**Comment by arbiocanpion** [comment]
Acabo de consultarlo, y la idea es que uses la estructura del Btree para iterar sobre las estructuras.
Igualmente, si ya tienes la idea de iterar sobre ambas listas, realizarla con el Btree no sera muy diferente.
¡Ánimo con la actividad!

**Comment by FloValdes** [comment]
Tengo que usar Btree para la parte 2.1? Hago un árbol con la lista R y otro con la lista S? O Btree es solo para 2.2

**Comment by arbiocanpion** [comment]
@FloValdes solo tienes que usar Btree para la parte 2.2.

**Comment by jerrymendoza** [comment]
Hola, aun me quedan dudas respecto a esto, hay que utilizar o no el btree en el 2.1 ? (pasar las listas a árbol y ordenarlo), en caso que no, puedo modificar las listas? (deque, iter.. etc)

**Comment by arbiocanpion** [comment]
@jerrymendoza  No es necesario que uses el Btree para la parte 2.1, pero si lo implementas para el Btree el item 2.2 sera mucho mas abordable, dado que para la parte 2.2 se te pide iterar sin usar indices, sobre el btree de usuarios y favoritos.

**Comment by rinorambuena** [comment]
Hola, y se puede usar la función `intersection` de BTrees.OOBTree o tengo que crear yo un código que realice la intersección?

**Comment by arpincheira** [comment]
@rinorambuena la idea de la actividad es que ustedes diseñen un algoritmo capaz de realizar la intersección, pero si quieres en un caso hipotético corroborar si es que el resultado de tu algoritmo es correcto podrías utilizar la función `intersection`.

**Comment by niguzman** [comment]
Hola,
sobre la 2.1 me queda la duda de que se refiere con que pase una sola vez por cada elemento
Puedo por ejemplo recorrer una lista e ir viendo si ese elemento está en la otra?

**Comment by Fenho** [comment]
En la 2.1, ¿Las iteraciones para hacer el BTree cuentan para las iteraciones del algoritmo? (que debe ser solo una por lista según el enunciado)

**Comment by arbiocanpion** [comment]
No, las iteraciones para generar el BTree no cuentan coomo iteraciones del algoritmo

**Comment by JJJGGGG** [comment]
Cual es el proposito de utilizar B+Trees en vez de listas ligadas? Pareciera que es redundante, si solo vamos a recorrer los valores en orden

**Comment by arbiocanpion** [comment]
La utilidad del B+Trees, es que ordenan de manera automatica las keys, es decir, permite que la lista ligada este en orden de menor a mayor. Igualmente como dije en la issue #96, es semejante a usar orderedDict(), pero con algunas funcionalidades menos.

**Comment by Fenho** [comment]
Se puede usar sort?

**Comment by arbiocanpion** [comment]
@Fenho, ¿Estas trabajando con la librería BTrees?

**Comment by Fenho** [comment]
planeaba usarla pero ordenando los elementos de mi lista antes
