### ISSUE TITLE
Actividad 3, ratings

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2413/Syllabus-2019-2#95]
Hola. En la actividad 3 se habla de una relación que se llama ```ratings```. Esta relacion no se encuentra en los archivos, pero yo supongo que se refiere a la relación ```favoritos```. Es esto así?

**Comment by arbiocanpion** [comment]
Hola!
Efectivamente, es un error de enunciado, la relación correcta es favoritos. 
Si descargas el jupyter que esta actualmente en el repositorio, notaras que esta corregido el error.
