### ISSUE TITLE
Duda parte 3 y 4: lista

### ISSUE THREAD

**Issue by clolate** [IIC2413/Syllabus-2019-2#97]
Cuando la parte 3 dice "... retorne una lista ..." y luego en la parte 4 dice: "reciba una lista [...] retornar una lista ... ", se refiere a un arreglo o a un BTree?

**Comment by arbiocanpion** [comment]
Hola!
Para la parte tres basta con que imprimas lo que te pedimos, es decir (nombre_usuario, userId, movieID, titulo_película).
Respecto a la parte 4 se refiere especificamente a una lista.
