### ISSUE TITLE
Orden y selección en NL-Join

### ISSUE THREAD

**Issue by viantirreau** [IIC2413/Syllabus-2019-2#98]
Hola!

Tengo dos dudas en la parte 4 de la actividad de índices y joins.
¿Es necesario que recorramos las estructuras de datos en este orden, o podemos cambiarlo?

```python
for usuario in usuarios:
    for favorito in favoritos: 
        for pelicula in peliculas: 
```

Y otra consulta, ¿puede haber selección _entre_ los loops? Es decir, algo de la forma

```python
for usuario in usuarios:
    if condicion1:
        for favorito in favoritos: 
            if condicion2:
                for pelicula in peliculas: 
                    if condicion3:
```

Siguiendo el mismo orden del enunciado y solo haciendo una selección en el loop interior (`condicion3`), el tiempo de ejecución es bastante, incluso con la base de datos `small`. Creo que no escalará bien a las bases más grandes :open_mouth: 

Gracias desde ya!

**Comment by arbiocanpion** [comment]
Hola!
Para efectos prácticos, recorre las tres listas con los for nada mas, ya que la idea es que ustedes puedan notar la diferencia de optimimalidad entre iterar sobre un Btree y listas comunes.

**Comment by mimunoz11** [comment]
¿la idea es que la parte 4, este hecha de forma no eficiente entonces? 

saludos

**Comment by arbiocanpion** [comment]
Por así decirlo si, ya que al hacer un join "a lo bruto" se realiza un proceso muy poco eficiente.

**Comment by BenjaPrograma** [comment]
> Asegúrate de hacer este experimento con ambos datasets.
 Como dijeron más arriba el tiempo es considerable incluso con los datos "small", ¿cómo lo hacemos entonces para los datos "big"?

**Comment by arbiocanpion** [comment]
Basta con que hagas notar en el análisis que el join solo con for's demora una cantidad bastante superior de tiempo, o si prefieres, puedes realizar algun tipo de proporción directa en base a la cantidad de datos que tenía small y el tiempo que demora, versus la cantidad de datos de big.

**Comment by imunoz3** [comment]
Hola! para la parte 2.2 y 3, mi código hace lo pedido (recorrer sólo 1 vez los datos) muy muy rápido para los datos small, pero para los datos big, se demora mucho. Significa que debo cambiar mi código para que sea más eficiente? o puedo hacer algún tipo de justificación de por qué se demora tanto con los big, en la parte 5.

**Comment by arbiocanpion** [comment]
@imunoz3  define mucho

**Comment by imunoz3** [comment]
Por ejemplo, en la parte 2.2 con los datos big, cuando hago un append de las tuplas correctas a una lista, pero sin imprimir cada una, el código se demora 2.4 s. Cuando imprimo cada linea, se demora aprox 10 minutos, pero jupyter colapsa y no me muestra todas las lineas. Es necesario que haya un print en esa parte?
